---
title: "5: Geospatial in R"
duedate: "{{< var duedates.lab5 >}}"
---



::: {.callout-warning}
## Due Date
This assignment is due on **{{< meta duedate >}}**
:::

{{< var blurbs.homeworkdue >}}




This assignment builds from the course materials for this week. Your assignment is to make a map of the change in an interesting census variable for your home county. If your home county is outside the US, you can use any county you like.


::: {.callout-note}

## Exercise 1 of 1

1. Load up all the necessary packages

2. Find the FIPS for your home county

3. Choose a variable you're interested in. It can be an ACS or PUMS variable, but it has to be different from any of those we used in class.

4. Using `get_acs()` or `get_pums()`, create a dataset with two different time periods and calculate the *change* in that variable between the time periods. If you use PUMs data, you'll have to summarize the data for each PUMA in your county. Your county may have only one PUMA, or may even share its PUMA with other counties. That's fine.

5. Make a map of that variable at the census tract level showing the difference over time. Make sure you label it clearly!

6. Write a few sentences describing the result and why you chose to that variable. Are there areas with more/less change? Based on what you know of your area, why?

:::
