---
title: "Assignments"
sidebar: assignments
toc: false
format: 
  html:
    code-fold: false
    code-tools: false
editor: source
---

<!-- Ben -- F25, I have removed the scoring rubric for the final project as it makes more sense to have it in the assignment (to mitigate conflicts and for clarity). -->

This course is the capstone of the Data Analytics Minor in the College of Social Science. Accordingly, you should---fingers crossed---enjoy data analysis. You will get the most of out this class if you:

1. Engage with the readings and lecture materials
2. Regularly use `R` (aka engage daily or almost every day in some way)

Assignments consist of **Weekly Writings** and **Lab Assignments**. Each type of assignment in this class helps with one of these strategies. Weekly writings engage with the materials, and lab assignments engage directly with `R`. The assignments are described below.

To get started, download and save the following files (**right-click** to Save Link As...)

- {{< var blurbs.writingtemplate >}}

- {{< var blurbs.labtemplate >}}


## Weekly Writings 

To encourage you to actively engage with the course content, you will write a ≈150 word memorandum about the reading or lecture each week. That's fairly short: there are ≈250 words on a typical double-spaced page. You must complete eleven of these in the course. I will drop your one lowest weekly writing score. Your actual prompt will be assigned **in class**, so you must login each day to ensure you get these assignments. To keep you on your toes, we will vary whether these are assigned on Tuesdays or Thursdays. **Each week's weekly writing will be due on D2L by 11:59pm on Saturday**

You can do a lot of different things with this memo: discuss something you learned from the course content, write about the best or worst data visualization you saw recently, connect the course content to your own work, etc. These reflections let you explore and answer some of the key questions of this course, including:

- When is a link correlational vs causal? How can we still make useful statements about non-causal things?
- Why do we visualize data?
- What makes a great data analysis? What makes a bad analysis?
- How do you choose which kind of analysis method to use?
- What is the role of the data structure in choosing an analysis? Can we be flexible?

The course content for each day will also include a set of questions specific to that topic. *You do not have to answer all (or any) of these questions*. That would be impossible. They exist to guide your thinking and to make complex reading more digestible. The specific topic for each week will be assigned **in class**. (We can't emphasize this enough.)

The TA will grade these mini-exercises using a very simple system:

- ✔+: (*6 points (100%) in gradebook*) Work is thoughtful, well-written, and shows engagement with the course content. This is the expected level of performance.
- ✔: (*5 points (83%) in gradebook*) Work shows bare minimum of thought and engagement. Disappointing, but excusable occasionally.
- ✔−: (*3 points (50%) in gradebook*) Work is hastily composed, too short, poorly formatted without headers, and/or only cursorily engages with the course content. This grade signals that you need to improve significantly next time. I will hopefully not assign these often.
- 0: (*0 points (0%) in gradebook*) Work is wholly uninformed by the prompt and/or written to the wrong prompt, or is not rendered using latex in Rmarkdown (e.g. html or word docs that are saved as pdf's).

(There is an implicit 0 above for work that is not turned in by Saturday at 11:59pm). Notice that this is essentially a pass/fail or completion-based system. We're not grading your writing ability; we're not counting the exact number of words you're writing; and we're not looking for encyclopedic citations of every single reading to prove that you did indeed read everything. We are looking for thoughtful engagement. Read the material, engage with the work and you'll get a ✓.

### Weekly Writing Template

You will turn these reflections in via D2L. You will write them using `R Markdown` and this template {{< var blurbs.writingtemplate >}}. You must `knit` your work to a PDF document (this will be what you turn in). D2L will have eleven weekly writing assignments available. Upload your first weekly writing assignment to number 1, your second (regardless of which week you are writing on) to number 2, etc. All work must be rendered using latex to PDF. Do **not** use word or html docs saved as a PDF. 




## Lab Assignments

Each week of the course has examples of code that teach and demonstrate how to do specific tasks in `R`. However, without practicing these principles and making graphics on your own, you won't remember what you learn.

Please do not do labs more than one week ahead of time. **I am updating the assignments as the semester proceeds, and you may do an entire assignment that is completely changed**. 

For example, to practice working with **ggplot2** and making data-based graphics, you will complete a brief set of exercises over a few class sessions. These exercises will have 1–3 short tasks that are directly related to the topic for the week. You need to show that you made a good faith effort to work each question. There will also be a final question which requires significantly more thought and work. This will be where you get to show some creativity and stretch your abilities. Overall, labs will be graded the same check system:

- ✔+: (*12 points (100%) in gradebook*) Exercises are complete. Every task was attempted and answered, and all answers are correct in detail. Knitted document is clean and easy to follow. Work on the final problem shows creativity or is otherwise exceptional. We will not assign these often.
- ✔: (*11 points (91%) in gradebook*) Exercises are complete and most answers are correct. Document is correctly formatted with few minor formatting errors. This is the expected level of performance.
- ✔−: (*6 points (50%) in gradebook*) Exercises are less than 70% complete and/or most answers are incorrect. Document is poorly formatted without appropriately rendered headers. This indicates that you need to improve next time. We will hopefully not assign these often.
- 0: (*0 points (0%) in gradebook*) Exercises are less than 50% complete, are grossly incorrect, or clearly do not follow the questions. Or, knitted document is not rendered via latex to PDF.

There is an implicit 0 for any assignment not turned in on time. If you have only partial work, then turn that in for partial credit. As noted in the syllabus, we are not grading your coding ability. We are not checking each line of code to make sure it produces some exact final figure, and we do not expect perfection. Also note that a ✓ does not require 100% success. You will sometimes get stuck with weird errors that you can't solve, or the demands of pandemic living might occasionally become overwhelming. We are looking for good faith effort. Try hard, engage with the task, and you'll get a ✓.

You may work together on the labs, but you must turn in your own answers. 

### Lab Template

You will turn these labs in via D2L. You will write them using `R Markdown` and this {{< var blurbs.labtemplate >}}. You must `knit` your work to a PDF document (this will be what you turn in). Your output must be rendered in latex. I do not accept rendering to HTML or Word and then converting to PDF and unrendered `.rmd` files are not allowed.


## Projects

To give you practice with the data and design principles you'll learn in this class, you will complete two projects en route to the overarching final project of the course. **Both these mini projects and the final project must be completed in groups.** I will assign groups after the drop deadline passes. Groups will be 2-3 people. You are allowed to form your own groups, but I will assign groups. More details will follow later.

The projects are checkpoints to ensure you're working on your project seriously. They will be graded using a continuous 0-100% scoring.

Because these mini projects give you practice for the final project, we will provide you with substantial feedback on your design and code.

