project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
    - "!projects/"
    - "!templates/"
  output-dir: _docs
  resources:
    - "files/"
    - "content/"
    - "projects/"

  preview:
    port: 4321
    browser: true

execute:
  freeze: auto
  warning: false
  message: false
  

website:
  title: "EC242"
  search: 
    # show-item-context: tree invalid for some reason?
    location: navbar
    type: textbox
  navbar:
    logo: "/images/Spartan-Helmet_White.png"
    background: "#18453b"
    right:
      - href: schedule.qmd
        text: Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: content/index.qmd
        text: "Course Content"
      - href: assignment/index.qmd
        text: "Lab Assignments"
      - href: resource/index.qmd
        text: "Resources"
      - icon: slack
        href: https://ec242.slack.com
  sidebar:
    - id: contents
      title: "help"
      style: "docked"
      search: true
      contents: content
      
    - id: assignments
      title: "Lab Assignments"
      style: "docked"
      search: true
      contents: assignment
    
    - id: main
      title: "maintitle"
      style: "docked"
      search: false
      contents:
        - text: "Welcome"
  
  page-navigation: false




format:
  html:
    theme: 
      - yeti
      - yetiADD.scss
    css: styles.css
    mainfont: "Fira Sans Condensed"
    toc: true
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true

editor: source

