project:
  type: website
  render:
    - "*.qmd"
    - "!*.Rmd"
    - "!*.rmd"
    #- "!Week_01/"
    #- "!Week_02/"
    #- "!Week_03/"
    #- "!Week_04/"
    #- "!Week_05/"
    #- "!Week_06/"
    #- "!Week_07/"
    #- "!Week_08/"
    #- "!Week_09/"
    #- "!Week_10/"
    #- "!Week_11/"
    #- "!Week_12/"
    #- "!Week_13/"
    #- "!Week_14/"
    #- "!Week_15/"
    #- "!*/01-assignment.qmd"
    #- "!*/02-assignment.qmd"
    #- "!*/03-assignment.qmd"
    #- "!*/04-assignment.qmd"
    #- "!*/05-assignment.qmd"
    #- "!*/06-assignment.qmd"
    #- "!*/07-assignment.qmd"
    #- "!*/08-assignment.qmd"
    #- "!*/09-assignment.qmd"
    #- "!*/10-assignment.qmd"
    #- "!*/11-assignment.qmd"
    #- "!*/12-assignment.qmd"
    #- "!*/13-assignment.qmd"
    #- "!*/14-assignment.qmd"
    #- "!*/15-assignment.qmd"
    #- "!groupproject/final-project.qmd"
    #- "!groupproject/project1.qmd"
    #- "!groupproject/project2.qmd"
    - "!groupproject/project2_OLD.qmd"
    - "!slides/"
    - "!templates/"
  output-dir: _docs
  resources:
    - "files/"
    - "content/"
    - "projects/"
    - "data/"
  

  preview:
    port: 4321
    browser: true

execute:
  freeze: auto
  warning: false
  message: false
  error: false
  

website:
  title: "EC242"
  announcement:
    icon: info-circle
    dismissable: true
    content: "I have allowed a 2nd dropped lab as of 12-3-2024"
    type: primary
    position: below-navbar
  search: 
    show-item-context: tree
    location: navbar
    type: textbox
  navbar:
    logo: "/images/Spartan-Helmet_White.png"
    # logo: "/images/plume.png"
    background: "#18453b"
    right:
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: content/index.qmd
        text: "Course Content"
      - href: assignment/index.qmd
        text: "Assignments"
      - href: resource/index.qmd
        text: "Resources"
      - icon: slack
        href: "{{< var slack.linkclean >}}"
  sidebar:
    - id: contents
      style: "docked"
      search: true
      contents: content
      
    - id: assignments
      style: "docked"
      search: true
      contents: 
        - section: "Lab Assignments"
          contents: assignment
        - section: "Group Projects"
          contents: 
            - groupproject/project1.qmd
            - groupproject/project2.qmd
            - groupproject/final-project.qmd
            
    - id: resources
      style: "docked"
      search: true
      contents: 
        - section: "Getting Started in R"
          contents:
            - resource/install.qmd
            - resource/RstudioCloud.qmd
            - resource/style.qmd
        - section: "Markdown"
          contents:
            - resource/markdown.qmd
            - resource/rmarkdown.qmd
        - section: "Other Useful Stuff"
          contents: 
            - resource/data.qmd
            - resource/spatial.qmd
            - resource/unzipping.qmd
            - resource/visualization.qmd
            - resource/design.qmd
      
    # 
    # - id: main
    #   title: "maintitle"
    #   style: "docked"
    #   search: false
    #   contents:
    #     - text: "Welcome"
  
  page-navigation: false




format:
  html:
    theme: 
      - yeti
      - yetiADD.scss
    css: styles.css
    mainfont: "Fira Sans Condensed"
    toc: true
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true

editor: source

