project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
    - "!projects/"
    - "!templates/"
  output-dir: _docs
  resources:
    - "files/"
    - "content/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"
  preview:
    port: 4321
    browser: true

execute:
  freeze: auto
  warning: false
  message: false
  

website:
  title: "EC242"
  search: 
    # show-item-context: tree invalid for some reason?
    location: navbar
    type: textbox
  navbar:
    logo: "/images/Spartan-Helmet_White.png"
    background: "#18453b"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: content/index.qmd
        text: "Course Content"
      - href: assignment/index.qmd
        text: "Lab Assignments"
    right:
      - icon: github
        href: https://github.com
  sidebar:
    - id: contents
      title: "help"
      style: "docked"
      search: true
      contents: content
      
    - id: assignments
      title: "Lab Assignments"
      style: "docked"
      search: true
      contents: assignment
    
    - id: main
      title: "maintitle"
      style: "docked"
      search: false
      contents:
        - text: "Welcome"
  
  page-navigation: false




format:
  html:
    theme: 
      - yeti
      - yetiADD.scss
    css: styles.css
    mainfont: "Fira Sans Condensed"
    toc: true
    code-copy: true
    code-overflow: wrap

editor: source

