---
title: "Schedule"
toc: true
---

Below is a roadmap for the semester. Note that this will inevitably change from the first day you access this course. However, whatever is listed below should be considered canon. Accordingly, you should visit this page frequently throughout the term.

As mentioned in the syllabus, the course is structured by topics; each week introduces a new topic. Moreover, every week is divided into four important sections that you should engage with: principles, applications, weekly writings, and assignments.

### Overview

The class is structured in the following way: each week, you will have two readings - generally a "principles" first, then an "applications" second (though this couse has drifted from this paradigm). Read the first reading for the Week under [**Course Content**](/content/) before our first meeting, and the second before our second meeting of the week. In either Tuesday or Thursday class, you'll be given a prompt for your weekly writing, which is due at 11:59pm on Saturday (see [**assignments**](/assignment/) and the [**syllabus**](/syllabus.html) for more info.

- [**Tuesdays**](/content/) (<i class="fas fa-book-reader"></i>): This page the material that we will discuss in Tuesday classes. 

- [**Thursdays**](/content/) (<i class="fas fa-laptop-code"></i>): This page the material that we will discuss in Thursday classes. 

- [**Weekly Writings**](/assignment/#weekly-writings) ({{< fa pencil >}}): **Weekly writings are due each week on Saturday at 11:59PM (eastern)**. Each week's writing prompt is given _during_ lecture either Tuesday or Thursday

- [**Lab Assignments**](/assignment/#lab-assignments) (<i class="fas fa-pencil-ruler"></i>): This page contains the instructions for the weekly lab (1–4 brief tasks) and for the three projects + final project. **Labs are due by 11:59 PM (Eastern) on the following Monday.** Labs are in addition to weekly writings and projects.




::: {.callout-note}
## You should follow this general process (in order) each week:

- Do everything on the principles (<i class="fas fa-book-reader"></i>) page before Tuesday
- Come to the lecture on Tuesday.
- While "in class" on Thursday, work through the applications (<i class="fas fa-laptop-code"></i>) page
- Complete the weekly writing by Saturday - topic assigned in class, see [assignments](/assignment/index.html#weekly-writings) for details and template
- Complete the lab (<i class="fas fa-pencil-ruler"></i>) by Monday.
- As needed, come to office hours or ask on Slack
:::

---

## {{< fa calendar >}} Course Calendar

<!-- Oh lordy, a regular "pipes" table doesn't do spans for the headers, so this has to be used. THE ROWS HAVE TO LINE UP. Zoom out in your Rstudio and maximize the window to see/alter. -->
<!-- Holy crap -- shortcodes break the grid table layout, so you have to use html, making this even wider and more unwieldy. zoom out! -->

+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
| Week | Dates           | [Programming Foundations]{.h4}                   | Tuesdays                                                                  | Thursdays                                                            | Lab Assignment                                                               |
+:====:+:===============:+:================================================:+:=========================================================================:+:====================================================================:+:============================================================================:+
|  1   | Sep 1 & Sep 3   | (Re-)introduction to R                           | [<i class="fa-solid fa-book-open-reader"></i>](/content/Week_01/01a.html) | [<i class="fa-solid fa-laptop-code"></i>](/content/Week_01/01b.html) | [<i class='fa-solid fa-pencil-ruler'></i>](/assignment/01-assignment.html)   |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|  2   | Sep 8 & Sep 10  | Tidyverse & (Re-)introduction to ggplot          | [<i class="fa-solid fa-book-open-reader"></i>](/content/Week_02/02a.html) | [<i class="fa-solid fa-laptop-code"></i>](/content/Week_02/02b.html) | [<i class='fa-solid fa-pencil-ruler'></i>](/assignment/02-assignment.html)   |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|  3   | Sep 15 & Sep 17 | Effective visualization in theory and practice   | [<i class="fa-solid fa-book-open-reader"></i>](/content/Week_03/03a.html) | [<i class="fa-solid fa-laptop-code"></i>](/content/Week_03/03b.html) | [<i class='fa-solid fa-pencil-ruler'></i>](/assignment/03-assignment.html)   |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|  4   | Sep 22 & Sep 24 | Advanced Visualization & Data Wrangling          | [<i class="fa-solid fa-book-open-reader"></i>](/content/Week_04/04a.html) | [<i class="fa-solid fa-laptop-code"></i>](/content/Week_04/04b.html) | [<i class='fa-solid fa-pencil-ruler'></i>](/assignment/04-assignment.html)   |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|      |                 | [Data Analysis Foundations]{.h4}                 |                                                                           |                                                                      |                                                                              |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|  5   | Sep 29 & Oct 1  | Data Hunting                                     | [<i class="fa-solid fa-book-open-reader"></i>](/content/Week_05/05a.html) | [<i class="fa-solid fa-laptop-code"></i>](/content/Week_05/05b.html) | [<i class='fa-solid fa-pencil-ruler'></i>](/assignment/05-assignment.html)   |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|      | Sat Oct 3       | <i class='fa-solid star'></i>Project 1 Due       | [<i class="fa-solid fa-book-open-reader"></i>]{.text-light}               | [<i class="fa-solid fa-laptop-code"></i>]{.text-light}               | [<i class='fa-solid fa-pencil-ruler'></i>](/groupproject/project1.html)      |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|  6   | Oct 6 & Oct 8   | Uncertainty and Probability in R                 | [<i class="fa-solid fa-book-open-reader"></i>](/content/Week_06/06a.html) | [<i class="fa-solid fa-laptop-code"></i>](/content/Week_06/06b.html) | [<i class='fa-solid fa-pencil-ruler'></i>](/assignment/06-assignment.html)   |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|  7   | Oct 13 & Oct 15 | Linear Regression I                              | [<i class="fa-solid fa-book-open-reader"></i>](/content/Week_07/07a.html) | [<i class="fa-solid fa-laptop-code"></i>](/content/Week_07/07b.html) | [<i class='fa-solid fa-pencil-ruler'></i>](/assignment/07-assignment.html)   |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|  8   | Oct 20 & Oct 22 | Linear Regression II                             | [<i class="fa-solid fa-book-open-reader"></i>](/content/Week_08/08a.html) | [<i class="fa-solid fa-laptop-code"></i>](/content/Week_08/08b.html) | [<i class='fa-solid fa-pencil-ruler'></i>](/assignment/08-assignment.html)   |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|      | Sun Oct 25      | <i class='fa-solid star'></i>Project 2 Due       | [<i class="fa-solid fa-book-open-reader"></i>]{.text-light}               | [<i class="fa-solid fa-laptop-code"></i>]{.text-light}               | [<i class='fa-solid fa-pencil-ruler'></i>](/groupproject/project2.html)      |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|      | Oct 26 & Oct 27 | **Fall Break -- no class Tuesday**               | [<i class="fa-solid fa-book-open-reader"></i>]{.text-light}               | [<i class="fa-solid fa-laptop-code"></i>]{.text-light}               | [<i class='fa-solid fa-pencil-ruler'></i>]{.text-light}                      |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|  9   | Thu Oct 29 only | In-class Presentation of Project 2               | [<i class="fa-solid fa-book-open-reader"></i>]{.text-light}               | [<i class="fa-solid fa-laptop-code"></i>](/content/Week_09/09b.html) | [<i class='fa-solid fa-pencil-ruler'></i>](/assignment/09-assignment.html)   |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|  10  | Nov 3 & Nov 5   | Linear Regression III                            | [<i class="fa-solid fa-book-open-reader"></i>](/content/Week_10/10a.html) | [<i class="fa-solid fa-laptop-code"></i>](/content/Week_10/10b.html) | [<i class='fa-solid fa-pencil-ruler'></i>](/assignment/10-assignment.html)   |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|  11  | Nov 10 & Nov 12 | Nonlinear Regression                             | [<i class="fa-solid fa-book-open-reader"></i>](/content/Week_11/11a.html) | [<i class="fa-solid fa-laptop-code"></i>](/content/Week_11/11b.html) | [<i class='fa-solid fa-pencil-ruler'></i>](/assignment/11-assignment.html)   |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|  12  | Nov 17 & Nov 19 | Feature Selection and the Bias Variance Tradeoff | [<i class="fa-solid fa-book-open-reader"></i>](/content/Week_12/11a.html) | [<i class="fa-solid fa-laptop-code"></i>](/content/Week_12/11b.html) | [<i class='fa-solid fa-pencil-ruler'></i>](/assignment/12-assignment.html)   |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|      | Sat Nov 21      | <i class='fa-solid star'></i>Project 3 Due       | [<i class="fa-solid fa-book-open-reader"></i>]{.text-light}               | [<i class="fa-solid fa-laptop-code"></i>]{.text-light}               | [<i class='fa-solid fa-pencil-ruler'></i>](/groupproject/project3.html)      |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|      |                 | [Further Extensions]{.h4}                        |                                                                           |                                                                      |                                                                              |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|  13  | Tue Nov 24 only | Text as Data                                     | [<i class="fa-solid fa-book-open-reader"></i>](/content/Week_14/13a.html) | [<i class="fa-solid fa-laptop-code"></i>]{.text-light}               | [<i class='fa-solid fa-pencil-ruler'></i>](/assignment/14-assignment.html)   |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|      | Nov 26 & Nov 27 | **Thanksgiving -- no class Thursday**            | [<i class="fa-solid fa-book-open-reader"></i>]{.text-light}               | [<i class="fa-solid fa-laptop-code"></i>]{.text-light}               | [<i class='fa-solid fa-pencil-ruler'></i>]{.text-light}                      |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|  14  | Dec 1 & Dec 3   | Classification                                   | [<i class="fa-solid fa-book-open-reader"></i>](/content/Week_13/12a.html) | [<i class="fa-solid fa-laptop-code"></i>](/content/Week_13/12b.html) | [<i class='fa-solid fa-pencil-ruler'></i>](/assignment/13-assignment.html)   |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|      |                 | [Conclusions]{.h4}                               |                                                                           |                                                                      |                                                                              |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|  15  | Dec 8 & Dec 10  | Final project work and review                    | [<i class="fa-solid fa-book-open-reader"></i>]{.text-light}               | [<i class="fa-solid fa-laptop-code"></i>]{.text-light}               | [<i class='fa-solid fa-pencil-ruler'></i>]{.text-light}                      |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+
|      | Thurs Dec 17    | <i class='fa-solid star'></i>Final Project Due   | [<i class="fa-solid fa-book-open-reader"></i>]{.text-light}               | [<i class="fa-solid fa-laptop-code"></i>]{.text-light}               | [<i class='fa-solid fa-pencil-ruler'></i>](/groupproject/final-project.html) |
+------+-----------------+--------------------------------------------------+---------------------------------------------------------------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------+


Due dates listed here are the actual due dates. On occasion, due dates in D2L are incorrectly set when porting from previous semesters. In all cases of conflicts, the due dates listed here prevail.

```{r setup-calendar, echo=F, eval = F}
library(knitr)
library(kableExtra)

cat(data.frame(
  Week = paste0(1:4),
  Title = c('(Re-)Introduction to R','Programming basics, the tidyverse, and visualization','Visualization II','Visualization III'),
  Principles = paste0('[{{< fa book-reader >}}]',c(paste0('(/content/Week_0',1:4,'/0',1:4,'a.html)'))),
  Applications = paste0('[{{< fa laptop-code >}}]',c(paste0('(/content/Week_0',1:4,'/0',1:4,'b.html)'))),
  Assignment = paste0('[{{< fa pencil-ruler >}}]',c(paste0('(/content/Week_0',1:4,'/0',1:4,'b.html)')))) %>%
  kbl(format = 'html', escape = FALSE, align = "llccc"))


```
