<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Hunting II – EC242</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-3c971a50abf938e2c558b68b8408b4fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": "tree",
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../images/Spartan-Helmet_White.png" alt="" class="navbar-logo light-content">
    <img src="../../images/Spartan-Helmet_White.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">EC242</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../content/index.html" aria-current="page"> 
<span class="menu-text">Course Content</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../assignment/index.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resource/index.html"> 
<span class="menu-text">Resources</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://ec242.slack.com"> <i class="bi bi-slack" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://bit.ly/EC242b"> <i class="bi bi-caret-up-square" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../content/index.html">Course Content</a></li><li class="breadcrumb-item"><a href="../../content/Week_05/05a.html">Week 05</a></li><li class="breadcrumb-item"><a href="../../content/Week_05/05b.html">Data Hunting II</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
  <div id="quarto-announcement" data-announcement-id="0243f0d00e9bc183c797bf484963b877" class="alert alert-primary hidden"><i class="bi bi-info-circle quarto-announcement-icon"></i><div class="quarto-announcement-content">
<p>Welcome to Fall Semester 2026!</p>
</div><i class="bi bi-x-lg quarto-announcement-action"></i></div>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../content/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Content</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 01</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_01/01a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome To Data Analytics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_01/01b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Working with R and RStudio</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 02</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_02/02a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reintroducing the tidyverse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_02/02b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">(Re)introduction to Visualization</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 03</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_03/03a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Effective Visualizations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_03/03b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visualizations in Practice</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 04</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_04/04a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Advanced Visualizations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_04/04b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Wrangling</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Week 05</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_05/05a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spatial Data Wrangling and Data Hunting I</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_05/05b.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Data Hunting II</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 06</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_06/06a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability and Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_06/06b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Uncertainty</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 07</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_07/07a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations of Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_07/07b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Regression</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 08</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_08/08a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Regression II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_08/08b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Regression: Interpreting Coefficients</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 09</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_09/09b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Group Presentations</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 10</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_10/10a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Regression III</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_10/10b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model Selection in Linear Regression</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 11</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_11/11a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Nonparametric Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_11/11b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Nonparametric Regression II</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 12</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_12/11a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bias-Variance Tradeoff</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_12/11b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Shrinkage with LASSO, Ridge, and Random Forests</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 13</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_13/13a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Text as Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_13/13b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">No Class — Thanksgiving</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 14</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_14/14a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classification</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_14/14b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Illustrating Classification</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 15</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_15/15a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Census Data in R</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#reading" id="toc-reading" class="nav-link active" data-scroll-target="#reading">Reading</a></li>
  <li><a href="#guiding-questions" id="toc-guiding-questions" class="nav-link" data-scroll-target="#guiding-questions">Guiding Questions</a></li>
  <li><a href="#before-we-start" id="toc-before-we-start" class="nav-link" data-scroll-target="#before-we-start">Before we start:</a></li>
  <li><a href="#seeking-out-data" id="toc-seeking-out-data" class="nav-link" data-scroll-target="#seeking-out-data">Seeking out data</a>
  <ul class="collapse">
  <li><a href="#temporal-and-geospatial-granularity-of-data" id="toc-temporal-and-geospatial-granularity-of-data" class="nav-link" data-scroll-target="#temporal-and-geospatial-granularity-of-data">Temporal and geospatial granularity of data</a></li>
  <li><a href="#micro-data-vs.-summary-data" id="toc-micro-data-vs.-summary-data" class="nav-link" data-scroll-target="#micro-data-vs.-summary-data">Micro-data vs.&nbsp;summary data</a></li>
  </ul></li>
  <li><a href="#us-census" id="toc-us-census" class="nav-link" data-scroll-target="#us-census">US Census</a>
  <ul class="collapse">
  <li><a href="#us-census-datasets" id="toc-us-census-datasets" class="nav-link" data-scroll-target="#us-census-datasets">US Census Datasets</a></li>
  <li><a href="#obtaining-census-data" id="toc-obtaining-census-data" class="nav-link" data-scroll-target="#obtaining-census-data">Obtaining Census Data</a></li>
  <li><a href="#individual-pums-data" id="toc-individual-pums-data" class="nav-link" data-scroll-target="#individual-pums-data">Individual (PUMS) data</a></li>
  <li><a href="#decennialacs-summary-tables" id="toc-decennialacs-summary-tables" class="nav-link" data-scroll-target="#decennialacs-summary-tables">Decennial/ACS Summary tables</a></li>
  </ul></li>
  <li><a href="#other-data-sources" id="toc-other-data-sources" class="nav-link" data-scroll-target="#other-data-sources">Other data sources</a>
  <ul class="collapse">
  <li><a href="#extracting-from-arcgis-online" id="toc-extracting-from-arcgis-online" class="nav-link" data-scroll-target="#extracting-from-arcgis-online">Extracting from ArcGIS Online</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../content/index.html">Course Content</a></li><li class="breadcrumb-item"><a href="../../content/Week_05/05a.html">Week 05</a></li><li class="breadcrumb-item"><a href="../../content/Week_05/05b.html">Data Hunting II</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Data Hunting II</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- Ben: review coded answer to try-it at end. I've been emailing it to myself for class. -->
<!-- For 2026: Ope, only got to the rows part of ACS variable names (but spent first 10 mins on group project and finishing distance matrix). -->
<!-- Probably spent too long talking about data forms and such. -->
<section id="reading" class="level1">
<h1>Reading</h1>
</section>
<section id="guiding-questions" class="level1">
<h1>Guiding Questions</h1>
<ul>
<li><p>Where do we find (social science) data “in the wild”?</p></li>
<li><p>What challenges are presented in finding data?</p></li>
<li><p>How is US census microdata structured?</p></li>
<li><p>How is US census summary data structured?</p></li>
<li><p>How can we obtain and work with useful samples of US Census data.</p></li>
</ul>
</section>
<section id="before-we-start" class="level1">
<h1>Before we start:</h1>
<p>You must obtain a US Census API key, which is free and fast. Go to <a href="https://api.census.gov/data/key_signup.html">https://api.census.gov/data/key_signup.html</a>. Then, install the <code>tidycensus</code> package and, once loaded, run <code>tidycensus::census_api_key('your census API key')</code> once and only once. It will save the key on your computer and won’t expose it in your code.</p>
</section>
<section id="seeking-out-data" class="level1">
<h1>Seeking out data</h1>
<p>We start our investigation of a social science question by asking “what sort of data can we bring to bear on this question”. Sometimes, this is obvious: if we’re interested in food deserts, we’d want some data on market locations, and some data on poverty in different areas, and we’d be able to see how many poor neighborhoods have (or do not have) access to fresh fruits and vegetables.</p>
<p>Some questions are not as up-front and require thinking about what data we’ll need or, more likely, what data is available. A few points to consider when thinking about a question and data.</p>
<ol type="1">
<li>Consider what your “dream data” might look like.</li>
</ol>
<p>You likely won’t find “dream data”, but at least you’ll define what you’re looking for. Maybe you’re interested in household energy consumption by household wealth (“do rich people use more electricity?”). Your dream data would be a dataset of households with reported energy consumption (maybe multiple observations over time of the same household), and with household income attached. You aren’t going to find that (if you do, email me right away!), but maybe if you start there, you can find something close. Say, monthly energy consumption aggregated to zip code, to which you can attach zip code level average income. Starting with “dream data” helps you figure out what features of data you’re interested in.</p>
<ol start="2" type="1">
<li>Consider proxies</li>
</ol>
<p>Maybe you won’t ever see energy consumption and income, but maybe you can find something that tends to vary along with income. Say, education or house size? Of course, the latter presents an issue for energy consumption (larger houses use more electricity), but maybe education can be a reasonable proxy for income. The zipcode level income in (1) would be a good proxy for a household’s income, even if you don’t have data on each household’s income.</p>
<ol start="3" type="1">
<li>Subsets</li>
</ol>
<p>While dream data (or reasonable proxies) may not exist for the entire country, is it possible to find something close in a local region? Does your data exist for one (large) state? Or even a county? An electric utility? In a survey? You may have to trade off data coverage for data usefulness. That’s OK, you just want to think about the “external validity” of your analysis – if you are studying just one place (e.g.&nbsp;“Michigan”) do you expect the same thing to hold in, say, California or Florida?</p>
<section id="temporal-and-geospatial-granularity-of-data" class="level2">
<h2 class="anchored" data-anchor-id="temporal-and-geospatial-granularity-of-data">Temporal and geospatial granularity of data</h2>
<p>Data is often limited in some way for privacy. That is, you should never be able to identify a single person in publicly available data, even if you know something about them. While data users like us would prefer to have very exact physical locations (imagine you’d like to see proximity to a greenspace for people with different income levels), privacy concerns mean we often only get to see less <em>granular</em> geographic location (like “city” or “county”).</p>
<p>Temporal granularity refers to time, the number of times we observe the same unit of observation, or the number of times we see any data, or how detailed the recording is of when things occur in time.</p>
<section id="panel-data" class="level3">
<h3 class="anchored" data-anchor-id="panel-data">Panel Data</h3>
<p>When we see the same unit of observation at different points in time (yearly, decadally, etc.), and when we see more than one unit of observation, then we say we have “panel data”. Panel data is very useful because we can look at changes over time for multiple units of observation, and we can look at the ways in which different variables change over time, and whether they change together.</p>
<p>For example, if we see unemployment rate and average education level every year for every county in Michigan, we’d say “we have a panel of counties with yearly data.” A panel dataset might be individuals as well, as long as we observe the same individual multiple times. If we saw that counties with increasing unemployment rates over time also tend to have decreasing average educational attainment, we will have learned somehting about the relationship (correlation) between the two, even if different counties have very different “usual” levels of unemployment.</p>
</section>
<section id="repeated-cross-section" class="level3">
<h3 class="anchored" data-anchor-id="repeated-cross-section">Repeated cross-section</h3>
<p>If we have data where the same variable is measured at different points in time, but measured against a different sample from the same population at each time period, we call that a “repeated cross-section.” It’s not as useful as a panel, but it’s better than nothing. Later, we’ll work with the US Energy Information Administration’s RECS (Residential Energy Consumption Survey), which is taken every 10 years and surveys a sample of around 10,000 homes in the US. Since it’s different homes sampled every 10 years, it’s a “repeated cross-section”.</p>
</section>
<section id="cross-section-and-time-series" class="level3">
<h3 class="anchored" data-anchor-id="cross-section-and-time-series">Cross section and time series</h3>
<p>A “cross section” is just a sample at one point in time (or taken over an interval of time, but without reporting the time). A time series dataset is one where a single unit of observation is followed over multiple points in time. Both of these are less useful for analysis.</p>
</section>
</section>
<section id="micro-data-vs.-summary-data" class="level2">
<h2 class="anchored" data-anchor-id="micro-data-vs.-summary-data">Micro-data vs.&nbsp;summary data</h2>
<p>Microdata is data where each observation is an instance of something recorded in the data. For contrast, we may have data on shipments of dishwashers from an appliance distributor, aggregated to the month level. Maybe we see them split out by state of destination, or by customer (total sales units to customer X in month Y). This would be <em>summary</em> or <em>aggregated</em> data. <em>Microdata</em> in the same context would be sale-level records, one observation for each sale, including customer location and date. Of course, this could have varying levels of detail – exact date vs.&nbsp;month of sale, price vs.&nbsp;just quantity, etc. For privacy reasons, or sheer data size, we don’t often see microdata.</p>
<p>Below, we’ll see both US Census <em>summary table</em> data, and we’ll learn about US census microdata (PUMA).</p>
</section>
</section>
<section id="us-census" class="level1">
<h1>US Census</h1>
<p>There are many sources for data that we can use for social science research and analytics. Today’s class will focus on US Census data, but I’ll include some other common sources at the end. For the US Census, we’ll look at:</p>
<section id="us-census-datasets" class="level2">
<h2 class="anchored" data-anchor-id="us-census-datasets">US Census Datasets</h2>
<ul>
<li><p>Decennial census (every 10 years, 100% of population)</p>
<ul>
<li>Public Use Microdata</li>
<li>Summary tables</li>
</ul></li>
<li><p>American Community Survey (every year, 1% of population)</p>
<ul>
<li>Public Use Microdata</li>
<li>Summary tables</li>
</ul></li>
<li><p>American Housing Survey</p></li>
<li><p>Commute flows</p></li>
<li><p>Many more <a href="https://www.census.gov/data/datasets.html">available here</a>, though most do not have packaged API’s like ACS/Census.</p></li>
</ul>
<section id="summary-tables-cross-tabs-and-individual-data" class="level3">
<h3 class="anchored" data-anchor-id="summary-tables-cross-tabs-and-individual-data">Summary tables, cross-tabs, and individual data</h3>
<p>Most US Census data is used via summary tables, which report a single value for each spatial area (like a census tract). Average income by census tract, average age by county, etc. We often also use cross-tabs of summary files, which subdivides by two or more variables. For instance, summary data may be reported for average income <strong>by age</strong> by census tract, or average age <strong>by nationality of birth</strong> by county. The US census makes a lot of cross-tabs, but not every single combination you could imagine. Plus, they are limited by privacy, so they can’t subdivide to the point you can identify a person. For instance, “average income by exact age by number of kids by profession by time living in current house by census block” would absolutely identify an individual’s current income as they’d be the only one being averaged.</p>
<p>The US decennial census and the yearly 5-year and 1-year American Community Survery (ACS) report summary tables with very rich cross-tabs.</p>
<p><strong>Individual microdata</strong> allows for generating any cross-tab as individual data would contain all responses to all questions for the respondent. The US Census makes the ACS sample individual answers available to the public, along with the survey and codebook for translating responses. Of course, for privacy reasons, the geographic location provided with the individual data is limited. The finest area reported is the “PUMA” (Public Use Microdata Area), each of which contains at least 100,000 individuals. For example, the City of Detroit is comprised of 5 PUMAs.</p>
</section>
<section id="us-census-spatial-definitions" class="level3">
<h3 class="anchored" data-anchor-id="us-census-spatial-definitions">US Census Spatial definitions</h3>
<ul>
<li>Region</li>
<li>Division</li>
<li>Metropolitain Statistical Area (MSA)</li>
<li>Combined Statistical Areas (CSA)</li>
<li>State</li>
<li>County</li>
<li>PUMA</li>
<li>Tract (1,600 households, 4,000 people on average)</li>
<li>Blockgroup</li>
<li>Block</li>
<li>Many more (tribal areas, zip code ZCTAs, etc.)</li>
</ul>
<p>You can explore <a href="https://tigerweb.geo.census.gov/tigerweb/">all of the census geographies with the TIGER browser</a> (make sure you turn on roads to get a sense of where you’re looking).</p>
<section id="geoid" class="level4">
<h4 class="anchored" data-anchor-id="geoid"><a href="https://www.census.gov/programs-surveys/geography/guidance/geo-identifiers.html">GEOID</a></h4>
<p>The US Census has standardized a way of referring to each spatial unit (“geography”) in the census data. The GEOID can be of different lengths depending on what it’s pointing to, and when census geographies are perfectly nested, then the GEOID tells you which smaller units belong to which bigger units (tracts in county). The GEOID for smaller areas (tracts and below) changes when the boundaries get redrawn each decade, so you’ll often see GEOID10 or GEOID20 (for 2010 or 2020 censuses).</p>
<ul>
<li>First 2 are state</li>
<li>Next 3 are county FIPS</li>
<li>Next 6 are Tract</li>
<li>Next 1 is blockgroup</li>
<li>Last 4 are block (first block digit includes blockgroup)</li>
</ul>
<p>The GEOID for the census block containing the Abbot in downtown East Lansing is:</p>
<p><span class="math display">\[\underbrace{26}_{\text{state}}\overbrace{065}^{\text{county}}\underbrace{004100}_{\text{tract}}\overbrace{3009}^{\text{block}}\]</span></p>
<p>26 is the state, 065 is Ingham County, 004100 is the tract, 3 is the blockgroup and 009 is the block (3009 would be the complete block number). To give you an idea of scale, the Abbot is the entire census block.</p>
<p>Different data is reported at different levels. Most basic decennial data is available at the block level (population, race, housing units), but ACS measures like average income stop at the blockgroup, and “cross-tabs” are not always available at blockgroup or even sometimes tract level. For example, average income for females over 85 is a “cross-tab” (reported in a “summary table” since it’s summarizing a population within a geography), but since there aren’t very many 85 year olds in any block (40 houses), it’s unlikely that the cross-tab can be reported.</p>
<p>Since there are many census surveys (decennial and ACS) over time, we can obtain the data for different years. Decennial census access goes back to the 1940’s and earlier, while ACS starts in the early 2000’s.</p>
<p>Rule of thumb: you want your census data to be at the same spatial and temporal granularity of your other data. That is, if you have a count of “number of markets with fresh veggies” at the tract level from some source, you probably want to have things like “average income” reported at the tract level as well. If you only have the measure for one year, you probably just want the nearest year reported in the census. If you have it for multiple years, then you probably want the census product years that correspond.</p>
</section>
</section>
</section>
<section id="obtaining-census-data" class="level2">
<h2 class="anchored" data-anchor-id="obtaining-census-data">Obtaining Census Data</h2>
<p>Using the <code>tidycensus</code> package, we can easily obtain US census data. First, you must obtain a US Census API key, which is free and fast. Go to <a href="https://api.census.gov/data/key_signup.html">https://api.census.gov/data/key_signup.html</a>. Then, install the <code>tidycensus</code> package and, once loaded, run <code>tidycensus::census_api_key('your census API key')</code> once and only once. It will save the key on your computer and won’t expose it in your code. Handy!</p>
<p>Tidycensus can obtain data from both PUMS (individual) and from the summary tables for ACS and decennial censuses. The interface makes it easy to import data directly into your R session. The hard part, though, is knowing what to ask for.</p>
</section>
<section id="individual-pums-data" class="level2">
<h2 class="anchored" data-anchor-id="individual-pums-data">Individual (PUMS) data</h2>
<p>You can load into R the complete list of variables available for PUMS with the instructions <a href="https://walker-data.com/tidycensus/articles/pums-data.html">here</a>. PUMS reports both household-level responses and individuals. Individuals are “nested” in households, and each individual gets a person weight (<code>PWGTP</code>) while each household gets its own household weight (<code>WGTP</code>) – these tell you how many real people (or households) each record stands for. You can easily move between individual and household by using <code>dplyr::summarize</code> after grouping by the household identifier.</p>
<p>My preferred way of finding the right PUMA variable is to use the browser at <a href="https://data.census.gov/app/mdat/ACSPUMS1Y2024">https://data.census.gov/app/mdat/ACSPUMS1Y2024</a>. Choose a year and a sample to see the data browser. Clicking on a topic drop-down shows you the codebook for the variable – the translation between the (compact) data returned and it’s meaning. Click on <code>AGEP</code> and note that values of <code>0</code> mean “under 1 year” and values 1-99 indicate age of the individual (top-coded at 99 so there are no 101 year olds reported; they just get “99”).</p>
<p>If you select a few then click on “see data” it will give you totals for the whole US, and try to show you cross-tabs generated using this data. However, <em>if you record the variable names, we can import the individual observations using <code>tidycensus::get_pums()</code></em>. We’ll include the <code>PUMA</code> variable since this tells us which PUMA the person lives in. PUMAs are not uniquely numbered to the state, so if we’re doing anything interstate, we’ll need to <code>unite</code> the <code>ST</code> and <code>PUMA</code> columns. <code>tidycensus</code> takes both state and the PUMA number as an input.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidycensus)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tigris)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">progress_enabled =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>individual1 <span class="ot">=</span> tidycensus<span class="sc">::</span><span class="fu">get_pums</span>(<span class="at">variables =</span> <span class="fu">c</span>(<span class="st">'AGEP'</span>,<span class="st">'NATIVITY'</span>,<span class="st">'PUMA'</span>), </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">state =</span> <span class="st">'MI'</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">puma =</span> <span class="cn">NULL</span>, <span class="co"># will pull all PUMAs in state</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">year =</span> <span class="dv">2022</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">survey =</span> <span class="st">'acs1'</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(individual1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  SERIALNO      SPORDER  WGTP PWGTP  AGEP PUMA  ST    NATIVITY
  &lt;chr&gt;           &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   
1 2022GQ0000003       1     0    11    22 02600 26    1       
2 2022GQ0000042       1     0    46    18 00801 26    1       
3 2022GQ0000160       1     0     3    46 02800 26    1       
4 2022GQ0000162       1     0    12    62 01801 26    1       
5 2022GQ0000215       1     0    73    86 01002 26    1       
6 2022GQ0000244       1     0    24    71 02600 26    1       </code></pre>
</div>
</div>
<p>The <code>SERIALNO</code> column shows the household identifier, and <code>SPORDER</code> contains the individual identifier (so a unique person is SERIALNO - SPORDER).</p>
<p>We can immediately make our own visualization: how about the distribution of age by nativity?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(individual1 <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>         dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">NATIVITY =</span> <span class="fu">case_when</span>(NATIVITY<span class="sc">==</span><span class="dv">1</span> <span class="sc">~</span> <span class="st">'US-born'</span>,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                                            NATIVITY<span class="sc">==</span><span class="dv">2</span> <span class="sc">~</span> <span class="st">'Foreign born'</span>)), </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> AGEP, <span class="at">fill =</span> <span class="fu">as.factor</span>(NATIVITY))) <span class="sc">+</span> </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> .<span class="dv">33</span>) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age"</span>, <span class="at">y =</span> <span class="st">'Density'</span>, <span class="at">fill =</span> <span class="st">'Nativity'</span>) <span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05b_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" alt="Density plot showing frequency of each age separated by foreign- and US-born. The blue US-born population is higher up to age 18, then less frequent from 18 to 60, then more frequen from 60 to 80, then less frequent from 80 to 99" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can do this for any variable we find on the data browser. One cheat above: I plotted the raw PUMS records and ignored the person weights (<code>PWGTP</code>), so that’s the distribution of the <em>sample</em>, not of Michigan. We’ll deal with weights at the end of class.</p>
<section id="pums-maps" class="level3">
<h3 class="anchored" data-anchor-id="pums-maps">PUMS maps</h3>
<p>Summarizing and showing on a map is easy. First, we need to obtain the PUMA map for the year that corresponds to our data (they are updated every 10 years). Then, we need to <code>group_by</code> and <code>summarize</code> the individual data so that each PUMS has one value for each variable.</p>
<p>I’m interested in seeing where in MI there’s a big gap between native-born age and foreign-born age. I’ll first pull the PUMAS using <code>tigris::pumas()</code>, then merge it to my data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>MIpums <span class="ot">=</span> tigris<span class="sc">::</span><span class="fu">pumas</span>(<span class="at">state =</span> <span class="st">'MI'</span>, <span class="at">year =</span> <span class="dv">2022</span>, <span class="at">progress_bar =</span> <span class="cn">FALSE</span>)  <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  tigris<span class="sc">::</span><span class="fu">erase_water</span>(<span class="at">area_threshold =</span> .<span class="dv">95</span>) <span class="co"># fixes the Great Lakes boundary issue (erases the largest 1-.95=5% of lakes)</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>MIpums.merge <span class="ot">=</span> MIpums <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(PUMACE20, NAMELSAD20) <span class="sc">%&gt;%</span> <span class="co"># just keeping useful columns from tigris file</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(individual1 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(PUMA) <span class="sc">%&gt;%</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>              dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">avgAge.USborn =</span> <span class="fu">mean</span>(AGEP[NATIVITY<span class="sc">==</span><span class="dv">1</span>], <span class="at">na.rm=</span>T),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>                               <span class="at">avgAge.foreignborn =</span> <span class="fu">mean</span>(AGEP[NATIVITY<span class="sc">==</span><span class="dv">2</span>], <span class="at">na.rm=</span>T),</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>                               <span class="at">diffAvgAge =</span> avgAge.USborn <span class="sc">-</span> avgAge.foreignborn),</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="fu">c</span>(<span class="st">'PUMACE20'</span> <span class="ot">=</span> <span class="st">'PUMA'</span>))</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(MIpums.merge)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 5 fields
Geometry type: GEOMETRYCOLLECTION
Dimension:     XY
Bounding box:  xmin: -90.41839 ymin: 42.48914 xmax: -82.12297 ymax: 48.26268
Geodetic CRS:  NAD83
  PUMACE20                                               NAMELSAD20
1    00100                             Western Upper Peninsula PUMA
2    00200                             Eastern Upper Peninsula PUMA
3    00300                           Northeast Lower Peninsula PUMA
4    01300 Iosco, Gladwin, Roscommon, Ogemaw &amp; Arenac Counties PUMA
5    01600                   Tuscola, Sanilac &amp; Huron Counties PUMA
6    03100                                    St. Clair County PUMA
  avgAge.USborn avgAge.foreignborn  diffAvgAge                       geometry
1      45.75952           46.40385  -0.6443257 GEOMETRYCOLLECTION (MULTILI...
2      48.40300           49.14545  -0.7424574 GEOMETRYCOLLECTION (MULTILI...
3      49.64950           53.15909  -3.5095911 GEOMETRYCOLLECTION (MULTILI...
4      51.36252           61.96000 -10.5974773 GEOMETRYCOLLECTION (MULTILI...
5      47.07148           54.91176  -7.8402866 GEOMETRYCOLLECTION (MULTILI...
6      45.29903           61.25806 -15.9590354 GEOMETRYCOLLECTION (MULTILI...</code></pre>
</div>
</div>
<p>Now, we can plot this (or use <code>mapview</code> to explore interactively)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(MIpums.merge, <span class="fu">aes</span>(<span class="at">fill =</span> diffAvgAge, <span class="at">col =</span> diffAvgAge)) <span class="sc">+</span> <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_continuous</span>(<span class="at">guide =</span> <span class="st">'none'</span>) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">'Diff. in avg</span><span class="sc">\n</span><span class="st">age'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05b_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" alt="Map showing the difference in average age between US- and foreign-born poulation by PUMA." width="672"></p>
</figure>
</div>
</div>
</div>
<p>You now have a wealth of socio-economic microdata at your fingertips, all linked to a relatively granular spatial location.</p>
</section>
</section>
<section id="decennialacs-summary-tables" class="level2">
<h2 class="anchored" data-anchor-id="decennialacs-summary-tables">Decennial/ACS Summary tables</h2>
<p>Summary tables from decennial census or the ACS contain finer geographies (usually down to census block), but aggregate rather than giving individual observations. Many cross-tabs are calculated for each geography, so finding the right one can be tricky. Some tables report averages or shares (percent renters, average income) while some report total counts (count of renters, number of people earning between $25-35k).</p>
<p>While <code>tidycensus</code> provides a function to import the whole list of all variables, we can also use the <a href="https://data.census.gov">data.census.gov</a> website. We are looking for <strong>tables</strong>, so click on “explore tables”.</p>
<p>First thing we want to do is set our geography level (e.g.&nbsp;block, block-group, tract, county, etc.) so that we are searching for data that exists at the level we want. No sense in searching for something you want at the county level to find out it’s only available at the state level! On the left side under “geography” click on the level you want (say, “census tract”) then choose a random state and tract – you’re only using this to find the variable’s code, not to actually retrieve data. I always use the first county in Alabama just because it’s small-ish so it doesn’t take long to load up.</p>
<p>I’m also going to select the year 2022 by scrolling down and checking the 2022 box, just so we’re only looking at ACS census data (in a decennial year like 2020, the decennial tables show up mixed in with the ACS ones). Not all variables exist for all years (especially over long periods of time). I’m going to search “house heating fuel” to find the type of heating fuel used. I’ll select “B25117”, which is the variable ID number for “House Heating Fuel” data.</p>
<p>This is what you’ll see at this point – note the location and geography filter.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="../../images/census1.png" class="img-fluid figure-img" alt="Screenshot of data.gov showing B25117 'House Heating Fuel' highlighted and showing data for all tracts in one county" width="852"></p>
</figure>
</div>
</div>
</div>
<p>Let’s take a look at the columns that show up under “B25117”. For this (and any table starting with “B”), there are two columns for each census tract header. The first is the “Estimate” and the second is the “Margin of Error”. The MOE is there because this is a sample (ACS is 1% of the population each year). Decennial censuses are counts, so there is no MOE. Other tables will have more columns (cross-tabs or expressed as percent vs.&nbsp;counts). We’ll get there in a second.</p>
<p>Just “B25117” isn’t quite enough. You see that there are multiple numbers in each column – the “Total:”, then “Utility gas” then “Bottled, tank, or LP gas” etc. There’s also two groupings: “Owner occupied” and “Renter occupied”. To import this data to <code>R</code>, we have to identify which of these (possibly many) numbers we want for every tract.</p>
<p>Each of the rows is numbered, so if we want the total number of households in a tract that are counted for this variable, then our target is “B25117_001”. If we want the total number of owner-occupied households using electric heating, we want row 5. If we want the same for renter-occupied, we want 15. And if we want to calculate, say, the <em>shares</em> of households using electric heat among renter-occupied households, we’d want row 15 divided by row 12. When there are blank lines, you do not count those lines.</p>
<p>The “Total” (row 1) will be same for almost all variables we could choose in the same year, geography, and survey (2022 ACS) because the universe of households surveyed is the same for all the variables. Some tables will have different universes (“all non-family households”, for example), so we’ll have to pay attention to the table description. If we go to B11016 “Household Type by Household Size” and look at the same tract, we’ll see the same estimate, but other rows for that variable will be different.</p>
<p>Let’s pull data for the first county in Alabama (FIPS = 01001) so we can convince ourselves that data.gov and <code>tidycensus</code> yield the same data. We’ll calculate the fraction of households that heat with “Bottled, tank, or LP gas”, separately for owners and for renters. We’ll note that we need the following:</p>
<ul>
<li>Total owner-occupied (row 2)</li>
<li>Total owner-occupied using Bottled, tank or LP gas (row 4)</li>
<li>Total renter-occupied (row 12)</li>
<li>Total renter-occupied using Bottled, tank or LP gas (row 14)</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>AL.heat <span class="ot">=</span> <span class="fu">get_acs</span>(<span class="at">geography =</span> <span class="st">'tract'</span>, </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">variables =</span> <span class="fu">c</span>(<span class="st">'OwnerOccupied_total'</span> <span class="ot">=</span> <span class="st">'B25117_002'</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                                <span class="st">'OwnerOccupied_LPgas'</span> <span class="ot">=</span> <span class="st">'B25117_004'</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                                <span class="st">'RenterOccupied_total'</span> <span class="ot">=</span> <span class="st">'B25117_012'</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>                                <span class="st">'RenterOccupied_LPgas'</span> <span class="ot">=</span> <span class="st">'B25117_014'</span>),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">year =</span> <span class="dv">2022</span>, <span class="at">survey =</span> <span class="st">'acs5'</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">output =</span> <span class="st">'wide'</span>, <span class="co"># in "wide" format</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">state =</span> <span class="st">'01'</span>, <span class="at">county =</span> <span class="st">'001'</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">geometry =</span> <span class="cn">TRUE</span>, <span class="at">progress_bar =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(GEOID) <span class="co"># so 201 is on top</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(AL.heat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 10 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -86.51029 ymin: 32.424 xmax: -86.41135 ymax: 32.50516
Geodetic CRS:  NAD83
        GEOID                                         NAME OwnerOccupied_totalE
1 01001020100    Census Tract 201; Autauga County; Alabama                  519
2 01001020200    Census Tract 202; Autauga County; Alabama                  429
3 01001020300    Census Tract 203; Autauga County; Alabama                  912
4 01001020400    Census Tract 204; Autauga County; Alabama                 1306
5 01001020501 Census Tract 205.01; Autauga County; Alabama                  971
6 01001020502 Census Tract 205.02; Autauga County; Alabama                  697
  OwnerOccupied_totalM OwnerOccupied_LPgasE OwnerOccupied_LPgasM
1                   98                   11                   16
2                   96                    0                   13
3                  229                   28                   33
4                  182                    0                   13
5                  242                    0                   13
6                  200                   40                   60
  RenterOccupied_totalE RenterOccupied_totalM RenterOccupied_LPgasE
1                   181                    92                     0
2                   115                    56                     5
3                   393                   114                    38
4                   360                   154                     0
5                   812                   211                     0
6                   630                   183                     0
  RenterOccupied_LPgasM                       geometry
1                    13 MULTIPOLYGON (((-86.5091 32...
2                    10 MULTIPOLYGON (((-86.48122 3...
3                    52 MULTIPOLYGON (((-86.47087 3...
4                    13 MULTIPOLYGON (((-86.45394 3...
5                    13 MULTIPOLYGON (((-86.43816 3...
6                    13 MULTIPOLYGON (((-86.4335 32...</code></pre>
</div>
</div>
<p>The <code>variables</code> argument takes <em>named</em> vectors, and <code>tidycensus</code> uses the name you give it for each variable for the column it outputs (appending “E” and “M” for Estimate and MOE).</p>
<p>That first line of the results shows 519 owner-occupied households total, same as on data.gov. We have both the Estimate and the Margin of Error, so we want to drop those. Then we want to calculate our shares.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>AL.heat.proc <span class="ot">=</span> AL.heat <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">!</span><span class="fu">ends_with</span>(<span class="st">'M'</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">OwnerShareLPgas =</span> OwnerOccupied_LPgasE<span class="sc">/</span>OwnerOccupied_totalE,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">RenterShareLPgas =</span> RenterOccupied_LPgasE<span class="sc">/</span>RenterOccupied_totalE) <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(GEOID, NAME, <span class="fu">ends_with</span>(<span class="st">'gas'</span>))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(AL.heat.proc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 4 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -86.51029 ymin: 32.424 xmax: -86.41135 ymax: 32.50516
Geodetic CRS:  NAD83
        GEOID                                         NAME OwnerShareLPgas
1 01001020100    Census Tract 201; Autauga County; Alabama      0.02119461
2 01001020200    Census Tract 202; Autauga County; Alabama      0.00000000
3 01001020300    Census Tract 203; Autauga County; Alabama      0.03070175
4 01001020400    Census Tract 204; Autauga County; Alabama      0.00000000
5 01001020501 Census Tract 205.01; Autauga County; Alabama      0.00000000
6 01001020502 Census Tract 205.02; Autauga County; Alabama      0.05738881
  RenterShareLPgas                       geometry
1       0.00000000 MULTIPOLYGON (((-86.5091 32...
2       0.04347826 MULTIPOLYGON (((-86.48122 3...
3       0.09669211 MULTIPOLYGON (((-86.47087 3...
4       0.00000000 MULTIPOLYGON (((-86.45394 3...
5       0.00000000 MULTIPOLYGON (((-86.43816 3...
6       0.00000000 MULTIPOLYGON (((-86.4335 32...</code></pre>
</div>
</div>
<p>The second lines uses a <code>tidyselect</code> shortcut to select anything that does NOT (!) end with “M” (so that we lose the “margin of error” columns). Similarly, the last line selects the GEOID, NAME and the two new variables I just created.</p>
<p>We can grab the census tract polygons for Alabama and plot these. <strong>Or</strong> – as we already did above – we can pass <code>geometry = TRUE</code> to our <code>get_acs</code> call, and we’ll get the <code>tigris</code> polygons already attached for this county.</p>
<p>Not all tables have just the “Estimate” and “Margin of Error” column. Some, like “S1101” (Households and Families) have cross-tabs across the columns (AND cross-tabs down the rows!). That’s super helpful if we have a very narrowly defined population we’re interested in, but also makes things harder. Let’s find the S1101 data and look at it’s table layout:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="fu">here</span>(<span class="st">'images'</span>,<span class="st">'census2.png'</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="../../images/census2.png" class="img-fluid figure-img" alt="Data.gov table layout with multiple columns with different crosstabs for S1101 in the first county in Alabama" width="853"></p>
</figure>
</div>
</div>
</div>
<p>Now on the right we see sets of columns with different cross-tabs. Total is still there (note that it’s still 700, just as before), but now there’s a pair of columns for “Married-couple family household” and “Male householder, no spouse present, family household” and more. Let’s look at “Female householder, no spouse present, family household” and find out what fraction of these households own their own home.</p>
<p>We’ll need the following</p>
<ul>
<li>Total households (row 1, since we don’t count blanks)</li>
<li>Owner-occupied households (row 18, since we don’t count blanks but we do count X’s – an “(X)” just means the cell doesn’t apply to that column, and it still takes up a row)
<ul>
<li>Note that this is already in percentage, so we don’t really need the Total households.</li>
</ul></li>
</ul>
<p>But we’ll need them specifically for the “Female householder, no spouse present, family household” set of columns. That is the <strong>fourth</strong> set of columns, so we append it with “C04”</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>AL.fam <span class="ot">=</span> <span class="fu">get_acs</span>(<span class="at">geography =</span> <span class="st">'tract'</span>, </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">variables =</span> <span class="fu">c</span>(<span class="st">'TotalHouseholds'</span> <span class="ot">=</span> <span class="st">'S1101_C04_001'</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                                <span class="st">'PctFemaleNoSpouseFamily_OwnerOccupied'</span> <span class="ot">=</span> <span class="st">'S1101_C04_018'</span>),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">year =</span> <span class="dv">2022</span>, <span class="at">survey =</span> <span class="st">'acs5'</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">output =</span> <span class="st">'wide'</span>, <span class="co"># in "wide" format</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">state =</span> <span class="st">'01'</span>, <span class="at">county =</span> <span class="st">'001'</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">geometry =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(GEOID) <span class="sc">%&gt;%</span> <span class="co"># comes in out of order for some reason</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">!</span><span class="fu">ends_with</span>(<span class="st">'M'</span>))</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(AL.fam)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  GEOID       NAME                       TotalHouseholdsE PctFemaleNoSpouseFam…¹
  &lt;chr&gt;       &lt;chr&gt;                                 &lt;dbl&gt;                  &lt;dbl&gt;
1 01001020100 Census Tract 201; Autauga…               81                   59.3
2 01001020200 Census Tract 202; Autauga…              131                   74.8
3 01001020300 Census Tract 203; Autauga…              290                   84.8
4 01001020400 Census Tract 204; Autauga…              159                   74.2
5 01001020501 Census Tract 205.01; Auta…              196                   20.4
6 01001020502 Census Tract 205.02; Auta…              165                   38.2
# ℹ abbreviated name: ¹​PctFemaleNoSpouseFamily_OwnerOccupiedE</code></pre>
</div>
</div>
<p>Here, we see we get the expected number – 59.3% owner-occupied. Now we can confidently change the state and county to whatever we are interested in, add other variables, and make new calculations.</p>
<p>Not all tables have the same cross-tab-by-column paradigm. The Data Profiles (DP) tables have the letter “E” for estimate, “PE” for percent, and “M” and “PM” for the margin of error. All tables have some sort of structure we can derive from data.gov, but we might have to look closesly at that structure.</p>
<p>Luckily, there is a full catalog of the structure of data.gov that can be found here: <a href="https://api.census.gov/data/2022/acs/acs5.html">https://api.census.gov/data/2022/acs/acs5.html</a> (this is for ACS 5-year in 2022, change the address for other years and surveys). Clicking on “variables” shows all available variables for that survery and year. It’s a little tricky to use but knowing what you know now, you can parse it out if necessary. You can see the different tables on the left and click on “variables” to see the full structure. The 2nd column shows first <em>what</em> is being reported (estimate, margin of error, percent), then <code>!!</code> designates a category header. After the next <code>!!</code> (if any), the table reports the category’s total, and after the next <code>!!</code> it reports the subcategory’s name. You can think of it as “out of the 3rd total, how many are the 4th?”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>TRY IT
</div>
</div>
<div class="callout-body-container callout-body">
<section id="part-a" class="level3">
<h3 class="anchored" data-anchor-id="part-a">Part A:</h3>
<p>Let’s take a look at Ingham Co.&nbsp;(FIPS 26065), which is where we’re located. We’ll use the ACS 5-year survey for 2021, specifically the <code>DP04</code> data profiles. <a href="https://api.census.gov/data/2021/acs/acs5/profile/variables.html">Here are the DP table structures</a>. At the “county” level, let’s get a count of:</p>
<ol type="1">
<li>Total housing units</li>
<li>Total housing units that are mobile homes</li>
</ol>
<p>Write code that uses <code>get_acs</code> to pull those totals in count (estimate) form (not in percent). The variable ID should be <code>DP04</code> followed by the proper row. Use the DP table structure to figure out what to append to <code>DP04_</code>.</p>
</section>
<section id="part-b1" class="level3">
<h3 class="anchored" data-anchor-id="part-b1">Part B1:</h3>
<p>Let’s ask for the same data, but do it with PUMS data. Ingham County contains <strong>two</strong> PUMAs – MI 01802 and MI 01801 (each state repeats numbering, so state + PUMA number is unique). For the two Ingham County PUMAs, pull the same data as in Part A: total housing units and total housing units that are mobile homes. Do it for the 2021 5-year data.</p>
<p>This is a little tricky because there isn’t a “do you live in a mobile home” question. But there <strong>is</strong> a question about the type of structure you live in, and one of the codes for that variable is….mobile home. See <a href="https://api.census.gov/data/2021/acs/acs1.html">https://api.census.gov/data/2021/acs/acs1.html</a>, select the “Public Use Microdata Sample” variables, and search for “structure”. Use that table to tell which variables to ask for (or how to work with the variables it has available).</p>
<p>From your data, how many individuals live in a mobile home? Remember, each row is an individual, and each unique <code>SERIALNO</code> is a household.</p>
</section>
<section id="part-b2" class="level3">
<h3 class="anchored" data-anchor-id="part-b2">Part B2:</h3>
<p>Let’s compare the PUMS counts to the ACS 5-year count. <strong>Your goal here is to see if we can get (close to) ACS totals using the PUMS sample</strong>. The ACS reports households, so we’ll have to get to household counts rather than individuals.</p>
<p>Part B1 should result in 12,439 observations with 6,388 unique values (you can use <code>length(unique(Data$SERIALNO))</code> to see how many unique household SERIALNOs there are). We know that the structure type is the same for all invididuals in a household. And our Part A data showed number of housing <em>units</em> – vacant ones included, so don’t expect the two to line up exactly. So, we want to “collapse” our data by keeping only the unique values of <code>SERIALNO</code> and our housing variable. <em>We are also going to keep the <code>WGTP</code> weight column. This column tells us how much we need to weight each household observation in order to “blow up” to the total estimate.</em></p>
<p>The column(s) we don’t need are <code>SPORDER</code> (that’s what shows the individual responses, but the household responses are all the same within household), and we don’t need the individual weight <code>PWGTP</code>. We can use the <code>dplyr::distinct()</code> function, which returns the unique values of whatever data you give it, so <code>select()</code> first then pipe to <code>distinct()</code>. Hint: you should have 6,388 rows when done. Each row will represent a household PUMS observation in one of the two PUMAs in Ingham county.</p>
<p><strong>Weights</strong>: to “blow up” from the <em>PUMS</em> (sample) to the totals reported in the ACS, we need simply multiply by the weight <code>WGTP</code>. It’s pretty easy to do in a <code>summarize</code> call. Since you have both PUMAs in Ingham Co.&nbsp;you need only add them all together (once properly weighted).</p>
<p><strong>Calculate the PUMS-based total number of households and total number of households living in mobile homes. Compare them to the numbers from Part A, as reported by the ACS. Do they match? Are they kinda close?</strong></p>
</section>
</div>
</div>
</section>
</section>
<section id="other-data-sources" class="level1">
<h1>Other data sources</h1>
<p>Census data products are core resources in socio-economic research. But they are not the only games in town, of course. In this section, we discuss other data sources, and briefly introduce the use of API’s for accessing many other data sources.</p>
<section id="msu-available-data" class="level3">
<h3 class="anchored" data-anchor-id="msu-available-data">MSU-available data</h3>
<ul>
<li><a href="https://lib.msu.edu/data">MSU Data Librarian start page</a>
<ul>
<li>MSU-subscribed datasets, may of which (but not all) are available to undergraduates</li>
</ul></li>
<li><a href="https://www.deweydata.io/">Dewey Data Catalog</a>
<ul>
<li>Clearinghouse of usually-expensive data across 25+ providers. Some examples:
<ul>
<li>NatureQuant has urban heat indexes</li>
<li>RentHub has rental price data over time (microdata from listings)</li>
<li>ClimateCheck climate risk data</li>
<li>SafeGraph cellphone point locations</li>
<li>Much more</li>
</ul></li>
<li>Requires extracting data – no straightforward access protocol</li>
</ul></li>
</ul>
</section>
<section id="other-common-sources" class="level3">
<h3 class="anchored" data-anchor-id="other-common-sources">Other common sources</h3>
<ul>
<li>Published journal articles in many journals are required to post code and data for replication (unless private or confidential data is used).
<ul>
<li>In most cases, you can find the data and code in the journal’s repository</li>
<li>So if you don’t know where to find data, but you find research that covers what you’re intersted in, you can simply pull data from their repository.</li>
</ul></li>
<li>Government open data portals
<ul>
<li>Many state and local governments have open data portals with maps you can view and explore (see <a href="https://gis-michigan.opendata.arcgis.com">Michigan’s here: https://gis-michigan.opendata.arcgis.com</a>).</li>
<li>Many municipalities have something similar as well.</li>
<li>However, many times they do not have the “download all data” ability turned on. Fear not - <a href="#extracting-from-arcgis-online">see below</a> for instructions to extract from ArcGIS online hosted maps (a large majority of hosted maps).</li>
</ul></li>
<li>Google has a <a href="https://datasetsearch.research.google.com">dataset search page</a></li>
</ul>
</section>
<section id="extracting-from-arcgis-online" class="level2">
<h2 class="anchored" data-anchor-id="extracting-from-arcgis-online">Extracting from ArcGIS Online</h2>
<p>A large number of municipalities share their geospatial open data using ArcGIS maps. Problem is, they often don’t let you download (you can view and make little story maps, but can’t bring it into R to merge, etc.).</p>
<p>Here’s how most (but not all) ArcGIS-hosted spatial data can be obtained.</p>
<ol type="1">
<li><p>Install the <code>arcgis</code> and <code>arcgislayers</code> packages.</p></li>
<li><p>Find the map you want to extract. I’m going to go to the MI open data link at <a href="https://gis-michigan.opendata.arcgis.com">https://gis-michigan.opendata.arcgis.com</a> and pull up a map of Michigan EGLE (Environment, Great Lakes, and Energy) conservation easements <a href="https://gis-michigan.opendata.arcgis.com/datasets/f3ae9b93f8264699a5a5a1b51a4a46c8_1/explore?location=42.739688%2C-84.422098%2C15">see here</a>.</p></li>
<li><p>Click on the map to highlight some feature – it doesn’t matter which, we just want our browser to query the map.</p></li>
<li><p>Turn on your browser’s Web Inspector pane (on Safari, it’s under “Developer”. On Firefox, it’s CTRL+SHIFT+I)</p></li>
<li><p>Click on the “network” tab</p></li>
<li><p>In the “filter” or “filter URL” bar, type “query”. This will highlight one or more entries where the “feature server” or “map server” was queried (just one if you only clicked once). It may just say “query”.</p></li>
<li><p>Click on one and look at the URL or URL summary. You’re looking for an address that starts with the URL of the mapping site (for mine, gisagoegle.state.mi.us), then followed by <code>/arcgis/rest</code> and eventually ending with <code>/featureserver</code> or <code>mapserver</code> followed by a number. We want to copy everything up to and including the number after <code>featureserver</code> or <code>mapserver</code>. In this example, the full address we want to copy is: <code>https://gisagoegle.state.mi.us/arcgis/rest/services/EGLE/WrdOpenData/MapServer/1/</code>.</p></li>
<li><p>Using <code>arcgislayer</code>:</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arcgislayers)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>MI.easements.url <span class="ot">=</span> <span class="st">'https://gisagoegle.state.mi.us/arcgis/rest/services/EGLE/WrdOpenData/MapServer/1/'</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>MI.easements <span class="ot">=</span> <span class="fu">arc_open</span>(MI.easements.url) <span class="sc">%&gt;%</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arc_select</span>()</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(MI.easements)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 9 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 711852.2 ymin: 448737.2 xmax: 715152 ymax: 461692.5
Projected CRS: NAD83 / Michigan Oblique Mercator
  OBJECTID Id     Acres         MappingDate FileNumber County
1        1  1 0.5833177 2008-03-03 19:00:00 06-01-0018 Alcona
2        2  2 0.6375753 2008-03-03 19:00:00 03-01-0030 Alcona
3        3  3 5.1003871 2008-03-03 19:00:00 03-01-0030 Alcona
4        4  4 0.3197049 2008-03-03 19:00:00 03-01-0030 Alcona
5        5  5 0.2803897 2008-03-03 19:00:00 03-01-0030 Alcona
6        6  6 0.2680268 2008-03-03 19:00:00 03-01-0030 Alcona
              Township Shape.STArea() Shape.STLength()
1   Greenbush Township       2360.613         198.6734
2 Harrisville Township       2580.186         222.0932
3 Harrisville Township      20640.617        1520.8078
4 Harrisville Township       1293.805         233.1256
5 Harrisville Township       1134.702         165.4281
6 Harrisville Township       1084.670         151.5164
                        geometry
1 POLYGON ((711852.9 448749.2...
2 POLYGON ((714978.6 461686, ...
3 POLYGON ((715115.4 461691.2...
4 POLYGON ((715141.1 461692.1...
5 POLYGON ((715078.4 461676.5...
6 POLYGON ((715083.2 461611.3...</code></pre>
</div>
</div>
<p>And now it’s our own layer in R and we can merge, summarize, and analyze to our hearts content.</p>
<p>Note: if you are having trouble installing <code>arcgislayers</code> on a Windows machine (and your error is asking about an installation of Rust), then use the following to install from already-compiled binaries: <code>install.packages("arcgis", repos = c("https://r-arcgis.r-universe.dev", "https://cloud.r-project.org"), type = 'win.binary')</code></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>