<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Linear Regression: Interpreting Coefficients – EC242</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": "tree",
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../images/Spartan-Helmet_White.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">EC242</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../content/index.html" aria-current="page"> 
<span class="menu-text">Course Content</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../assignment/index.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resource/index.html"> 
<span class="menu-text">Resources</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://ec242.slack.com"> <i class="bi bi-slack" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../content/index.html">Course Content</a></li><li class="breadcrumb-item"><a href="../../content/Week_07/07a.html">Week 07</a></li><li class="breadcrumb-item"><a href="../../content/Week_07/07b.html">Linear Regression: Interpreting Coefficients</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../content/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Content</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 01</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_01/01a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome To Data Analytics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_01/01b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Working with R and RStudio</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 02</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_02/02a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to the tidyverse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_02/02b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Visualization</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 03</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_03/03a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Effective Visualizations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_03/03b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ggplot2: Everything you ever wanted to know</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 04</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_04/04a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visualizations in Practice</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_04/04b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visualizations</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 05</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_05/05a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability and Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_05/05b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visualizing Uncertainty</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 06</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_06/06a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations of Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_06/06b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Regression</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Week 07</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_07/07a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Regression II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_07/07b.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Linear Regression: Interpreting Coefficients</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 08</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_08/08a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Regression III</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_08/08b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model Selection in Linear Regression</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 09</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_09/09b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Shrinkage with LASSO and Ridge</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 10</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_10/10a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Nonparametric Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_10/10b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Nonparametric Regression</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 11</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_11/11b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bias-Variance Tradeoff and Random Forests</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 12</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_12/12a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classification</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Week_12/12b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Illustrating Classification</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#preliminaries" id="toc-preliminaries" class="nav-link active" data-scroll-target="#preliminaries">Preliminaries</a></li>
  <li><a href="#dummy-variables" id="toc-dummy-variables" class="nav-link" data-scroll-target="#dummy-variables">Dummy Variables</a></li>
  <li><a href="#interactions" id="toc-interactions" class="nav-link" data-scroll-target="#interactions">Interactions</a></li>
  <li><a href="#factor-variables" id="toc-factor-variables" class="nav-link" data-scroll-target="#factor-variables">Factor Variables</a></li>
  <li><a href="#parameterization" id="toc-parameterization" class="nav-link" data-scroll-target="#parameterization">Parameterization</a></li>
  <li><a href="#building-larger-models" id="toc-building-larger-models" class="nav-link" data-scroll-target="#building-larger-models">Building Larger Models</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../content/index.html">Course Content</a></li><li class="breadcrumb-item"><a href="../../content/Week_07/07a.html">Week 07</a></li><li class="breadcrumb-item"><a href="../../content/Week_07/07b.html">Linear Regression: Interpreting Coefficients</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Linear Regression: Interpreting Coefficients</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Today’s example will pivot between the content from this week and the example below.</p>
<p>We will also use the Ames data again. Maybe some new data. Who knows. The Ames data is linked below:</p>
<ul>
<li><a href="../..\projects/data/ames.csv"><i class="fas fa-file-csv"></i> <code>Ames.csv</code></a></li>
</ul>
</div>
</div>
<section id="preliminaries" class="level2">
<h2 class="anchored" data-anchor-id="preliminaries">Preliminaries</h2>
<p>So far in each of our analyses, we have only used numeric variables as predictors. We have also only used <em>additive models</em>, meaning the effect any predictor had on the response was not dependent on the other predictors. In this chapter, we will remove both of these restrictions. We will fit models with multiple predictors, categorical predictors, and use models that allow predictors to <em>interact</em>. Instead of a single variable, will use <em>multiple</em> linear regression. The mathematics of multiple regression will remain largely unchanging, however, we will pay close attention to interpretation, as well as some difference in <code>R</code> usage.</p>
</section>
<section id="dummy-variables" class="level2">
<h2 class="anchored" data-anchor-id="dummy-variables">Dummy Variables</h2>
<p>For this example and discussion, we will briefly use the built in dataset <code>mtcars</code> before introducing the <code>autompg</code> dataset. The reason to use these easy, straightforward datasets is that they make visualization of the <strong>entire dataset</strong> trivially easy. Accordingly, the <code>mtcars</code> dataset is small, so we’ll quickly take a look at the entire dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>mtcars</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8
Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2</code></pre>
</div>
</div>
<p>We will be interested in three of the variables: <code>mpg</code>, <code>hp</code>, and <code>am</code>.</p>
<ul>
<li><code>mpg</code>: fuel efficiency, in miles per gallon.</li>
<li><code>hp</code>: horsepower, in foot-pounds per second.</li>
<li><code>am</code>: transmission. Automatic or manual.</li>
</ul>
<p>As we often do, we will start by plotting the data. We are interested in <code>mpg</code> as the response variable, and <code>hp</code> as a predictor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> mtcars, <span class="at">cex =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07b_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Since we are also interested in the transmission type, we could also label the points accordingly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> mtcars, <span class="at">col =</span> am <span class="sc">+</span> <span class="dv">1</span>, <span class="at">pch =</span> am <span class="sc">+</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="fu">c</span>(<span class="st">"Automatic"</span>, <span class="st">"Manual"</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07b_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We now fit the SLR model</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 x_1 + \epsilon,\]</span></p>
<p>where <span class="math inline">\(Y\)</span> is <code>mpg</code> and <span class="math inline">\(x_1\)</span> is <code>hp</code>. For notational brevity, we drop the index <span class="math inline">\(i\)</span> for observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mpg_hp_slr <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We then re-plot the data and add the fitted line to the plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> mtcars, <span class="at">col =</span> am <span class="sc">+</span> <span class="dv">1</span>, <span class="at">pch =</span> am <span class="sc">+</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mpg_hp_slr, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"grey"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="fu">c</span>(<span class="st">"Automatic"</span>, <span class="st">"Manual"</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07b_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We should notice a pattern here. The red, manual observations largely fall above the line, while the black, automatic observations are mostly below the line. This means our model underestimates the fuel efficiency of manual transmissions, and overestimates the fuel efficiency of automatic transmissions. To correct for this, we will add a predictor to our model, namely, <code>am</code> as <span class="math inline">\(x_2\)</span>.</p>
<p>Our new model is</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \epsilon,
\]</span></p>
<p>where <span class="math inline">\(x_1\)</span> and <span class="math inline">\(Y\)</span> remain the same, but now</p>
<p><span class="math display">\[
x_2 =
  \begin{cases}
   1 &amp; \text{manual transmission} \\
   0       &amp; \text{automatic transmission}
  \end{cases}.
\]</span></p>
<p>In this case, we call <span class="math inline">\(x_2\)</span> a <strong>dummy variable</strong>. A dummy variable (also called an “indicator” variable) is somewhat unfortunately named, as it is in no way “dumb”. In fact, it is actually somewhat clever. A dummy variable is a numerical variable that is used in a regression analysis to “code” for a binary categorical variable. Let’s see how this works.</p>
<p>First, note that <code>am</code> is already a dummy variable, since it uses the values <code>0</code> and <code>1</code> to represent automatic and manual transmissions. Often, a variable like <code>am</code> would store the character values <code>auto</code> and <code>man</code> and we would either have to convert these to <code>0</code> and <code>1</code>, or, as we will see later, <code>R</code> will take care of creating dummy variables for us.</p>
<p>So, to fit the above model, we do so like any other multiple regression model we have seen before.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mpg_hp_add <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp <span class="sc">+</span> am, <span class="at">data =</span> mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Briefly checking the output, we see that <code>R</code> has estimated the three <span class="math inline">\(\beta\)</span> parameters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mpg_hp_add</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp + am, data = mtcars)

Coefficients:
(Intercept)           hp           am  
   26.58491     -0.05889      5.27709  </code></pre>
</div>
</div>
<p>Since <span class="math inline">\(x_2\)</span> can only take values <code>0</code> and <code>1</code>, we can effectively write two different models, one for manual and one for automatic transmissions.</p>
<p>For automatic transmissions, that is <span class="math inline">\(x_2 = 0\)</span>, we have,</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x_1 + \epsilon.
\]</span></p>
<p>Then for manual transmissions, that is <span class="math inline">\(x_2 = 1\)</span>, we have,</p>
<p><span class="math display">\[
Y = (\beta_0 + \beta_2) + \beta_1 x_1 + \epsilon.
\]</span></p>
<p>Notice that these models share the same slope, <span class="math inline">\(\beta_1\)</span>, but have different intercepts, differing by <span class="math inline">\(\beta_2\)</span>. So the change in <code>mpg</code> is the same for both models, but on average <code>mpg</code> differs by <span class="math inline">\(\beta_2\)</span> between the two transmission types.</p>
<p>We’ll now calculate the estimated slope and intercept of these two models so that we can add them to a plot. Note that:</p>
<ul>
<li><span class="math inline">\(\hat{\beta}_0\)</span> = <code>coef(mpg_hp_add)[1]</code> = 26.5849137</li>
<li><span class="math inline">\(\hat{\beta}_1\)</span> = <code>coef(mpg_hp_add)[2]</code> = -0.0588878</li>
<li><span class="math inline">\(\hat{\beta}_2\)</span> = <code>coef(mpg_hp_add)[3]</code> = 5.2770853</li>
</ul>
<p>We can then combine these to calculate the estimated slope and intercepts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>int_auto <span class="ot">=</span> <span class="fu">coef</span>(mpg_hp_add)[<span class="dv">1</span>]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>int_manu <span class="ot">=</span> <span class="fu">coef</span>(mpg_hp_add)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(mpg_hp_add)[<span class="dv">3</span>]</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>slope_auto <span class="ot">=</span> <span class="fu">coef</span>(mpg_hp_add)[<span class="dv">2</span>]</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>slope_manu <span class="ot">=</span> <span class="fu">coef</span>(mpg_hp_add)[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Re-plotting the data, we use these slopes and intercepts to add the “two” fitted models to the plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> mtcars, <span class="at">col =</span> am <span class="sc">+</span> <span class="dv">1</span>, <span class="at">pch =</span> am <span class="sc">+</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(int_auto, slope_auto, <span class="at">col =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="dv">2</span>) <span class="co"># add line for auto</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(int_manu, slope_manu, <span class="at">col =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>) <span class="co"># add line for manual</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="fu">c</span>(<span class="st">"Automatic"</span>, <span class="st">"Manual"</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07b_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We notice right away that the points are no longer systematically incorrect. The red, manual observations vary about the red line in no particular pattern without underestimating the observations as before. The black, automatic points vary about the black line, also without an obvious pattern.</p>
<p>They say a picture is worth a thousand words, but as a statistician, sometimes a picture is worth an entire analysis. The above picture makes it plainly obvious that <span class="math inline">\(\beta_2\)</span> is significant, but let’s verify mathematically. Essentially we would like to test:</p>
<p><span class="math display">\[
H_0: \beta_2 = 0 \quad \text{vs} \quad H_1: \beta_2 \neq 0.
\]</span></p>
<p>This is nothing new. Again, the math is the same as the multiple regression analyses we have seen before. We could perform either a <span class="math inline">\(t\)</span> or <span class="math inline">\(F\)</span> test here. The only difference is a slight change in interpretation. We could think of this as testing a model with a single line (<span class="math inline">\(H_0\)</span>) against a model that allows two lines (<span class="math inline">\(H_1\)</span>).</p>
<p>To obtain the test statistic and p-value for the <span class="math inline">\(t\)</span>-test, we would use</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mpg_hp_add)<span class="sc">$</span>coefficients[<span class="st">"am"</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Estimate   Std. Error      t value     Pr(&gt;|t|) 
5.277085e+00 1.079541e+00 4.888270e+00 3.460318e-05 </code></pre>
</div>
</div>
<p>To do the same for the <span class="math inline">\(F\)</span> test, we would use a call to <code>anova</code>. One way of comparing the fit of models (which accounts for the fact that one model is more “flexible” than another) is to use <code>anova</code>. The null hypothesis of the <code>anova</code> is that the two models explain the same amount of variation in the dependent variable (<code>mpg</code>). If we reject the F-test in the <code>anova</code> (if the p-value is small), then the more flexible model is actually explaining more. One caveat is that the models must be <em>nested</em> – one has to vary from the other only by omitting variables, not by omitting some and adding others. Here, <code>mpg_hp_slr</code> is nested in <code>mpg_hp_add</code> because it uses a subset of the variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mpg_hp_slr, mpg_hp_add)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: mpg ~ hp
Model 2: mpg ~ hp + am
  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)    
1     30 447.67                                 
2     29 245.44  1    202.24 23.895 3.46e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Notice that these are indeed testing the same thing, as the p-values are exactly equal. (And the <span class="math inline">\(F\)</span> test statistic is the <span class="math inline">\(t\)</span> test statistic squared.) This is only the case for different models that differ only by one additional variable.</p>
<p>Recapping some interpretations:</p>
<ul>
<li><p><span class="math inline">\(\hat{\beta}_0 = 26.5849137\)</span> is the estimated average <code>mpg</code> for a car with an automatic transmission and <strong>0</strong> <code>hp</code>.</p></li>
<li><p><span class="math inline">\(\hat{\beta}_0 + \hat{\beta}_2 = 31.8619991\)</span> is the estimated average <code>mpg</code> for a car with a manual transmission and <strong>0</strong> <code>hp</code>.</p></li>
<li><p><span class="math inline">\(\hat{\beta}_2 = 5.2770853\)</span> is the estimated <strong>difference</strong> in average <code>mpg</code> for cars with manual transmissions as compared to those with automatic transmission, for <strong>any</strong> <code>hp</code>.</p></li>
<li><p><span class="math inline">\(\hat{\beta}_1 = -0.0588878\)</span> is the estimated change in average <code>mpg</code> for an increase in one <code>hp</code>, for <strong>either</strong> transmission types.</p></li>
</ul>
<p>We should take special notice of those last two. In the model,</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \epsilon,
\]</span></p>
<p>we see <span class="math inline">\(\beta_1\)</span> is the average change in <span class="math inline">\(Y\)</span> for an increase in <span class="math inline">\(x_1\)</span>, <em>no matter</em> the value of <span class="math inline">\(x_2\)</span>. Also, <span class="math inline">\(\beta_2\)</span> is always the difference in the average of <span class="math inline">\(Y\)</span> for <em>any</em> value of <span class="math inline">\(x_1\)</span>. These are two restrictions we won’t always want, so we need a way to specify a more flexible model.</p>
<p>Here we restricted ourselves to a single numerical predictor <span class="math inline">\(x_1\)</span> and one dummy variable <span class="math inline">\(x_2\)</span>. However, the concept of a dummy variable can be used with larger multiple regression models. We only use a single numerical predictor here for ease of visualization since we can think of the “two lines” interpretation. But in general, we can think of a dummy variable as creating “two models,” one for each category of a binary categorical variable.</p>
</section>
<section id="interactions" class="level2">
<h2 class="anchored" data-anchor-id="interactions">Interactions</h2>
<p>To remove the “same slope” restriction, we will now discuss <strong>interactions</strong>. To illustrate this concept, we will use the <code>autompg</code> dataset with a few modifications.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read data frame from the web</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>autompg <span class="ot">=</span> <span class="fu">read.table</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data"</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">quote =</span> <span class="st">"</span><span class="sc">\"</span><span class="st">"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">comment.char =</span> <span class="st">""</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># give the dataframe headers</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(autompg) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"mpg"</span>, <span class="st">"cyl"</span>, <span class="st">"disp"</span>, <span class="st">"hp"</span>, <span class="st">"wt"</span>, <span class="st">"acc"</span>, <span class="st">"year"</span>, <span class="st">"origin"</span>, <span class="st">"name"</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>autompg <span class="ot">=</span> autompg <span class="sc">%&gt;%</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(hp <span class="sc">!=</span><span class="st">'?'</span> <span class="sc">&amp;</span> name <span class="sc">!=</span><span class="st">'plymouth reliant'</span>) <span class="sc">%&gt;%</span> <span class="co"># the reliant causes some issues</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hp =</span> <span class="fu">as.numeric</span>(hp),</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">domestic =</span> <span class="fu">as.numeric</span>(origin<span class="sc">==</span><span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>cyl <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">3</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cyl =</span> <span class="fu">as.factor</span>(cyl))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(autompg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   383 obs. of  10 variables:
 $ mpg     : num  18 15 18 16 17 15 14 14 14 15 ...
 $ cyl     : Factor w/ 3 levels "4","6","8": 3 3 3 3 3 3 3 3 3 3 ...
 $ disp    : num  307 350 318 304 302 429 454 440 455 390 ...
 $ hp      : num  130 165 150 150 140 198 220 215 225 190 ...
 $ wt      : num  3504 3693 3436 3433 3449 ...
 $ acc     : num  12 11.5 11 12 10.5 10 9 8.5 10 8.5 ...
 $ year    : int  70 70 70 70 70 70 70 70 70 70 ...
 $ origin  : int  1 1 1 1 1 1 1 1 1 1 ...
 $ name    : chr  "chevrolet chevelle malibu" "buick skylark 320" "plymouth satellite" "amc rebel sst" ...
 $ domestic: num  1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>We’ve removed cars with <code>3</code> and <code>5</code> cylinders , as well as created a new variable <code>domestic</code> which indicates whether or not a car was built in the United States. Removing the <code>3</code> and <code>5</code> cylinders is simply for ease of demonstration later in the chapter and would not be done in practice. The new variable <code>domestic</code> takes the value <code>1</code> if the car was built in the United States, and <code>0</code> otherwise, which we will refer to as “foreign.” (We are arbitrarily using the United States as the reference point here.) We have also made <code>cyl</code> and <code>origin</code> into factor variables, which we will discuss later.</p>
<p>We’ll now be concerned with three variables: <code>mpg</code>, <code>disp</code>, and <code>domestic</code>. We will use <code>mpg</code> as the response. We can fit a model,</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \epsilon,
\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(Y\)</span> is <code>mpg</code>, the fuel efficiency in miles per gallon,</li>
<li><span class="math inline">\(x_1\)</span> is <code>disp</code>, the displacement in cubic inches,</li>
<li><span class="math inline">\(x_2\)</span> is <code>domestic</code> as described above, which is a dummy variable.</li>
</ul>
<p><span class="math display">\[
x_2 =
  \begin{cases}
   1 &amp; \text{Domestic} \\
   0 &amp; \text{Foreign}
  \end{cases}
\]</span></p>
<p>We will fit this model, extract the slope and intercept for the “two lines,” plot the data and add the lines.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mpg_disp_add <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">+</span> <span class="fu">as.factor</span>(domestic), <span class="at">data =</span> autompg)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>int_for <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_add)[<span class="dv">1</span>]</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>int_dom <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_add)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(mpg_disp_add)[<span class="dv">3</span>]</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>slope_for <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_add)[<span class="dv">2</span>]</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>slope_dom <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_add)[<span class="dv">2</span>] <span class="co">#--&gt; same slope!</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(autompg, <span class="fu">aes</span>(<span class="at">x =</span> disp, <span class="at">y =</span> mpg, <span class="at">col =</span> <span class="fu">as.factor</span>(domestic))) <span class="sc">+</span> </span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> int_dom, </span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope =</span> slope_dom, <span class="at">col =</span> <span class="st">'blue'</span>) <span class="sc">+</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> int_for,</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope =</span> slope_for, <span class="at">col =</span> <span class="st">'red'</span>) <span class="sc">+</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">'Origin'</span>) <span class="sc">+</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Foreign'</span>,<span class="st">'Domestic'</span>), <span class="at">values =</span> <span class="fu">c</span>(<span class="st">'red'</span>,<span class="st">'blue'</span>)) <span class="sc">+</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07b_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This is a model that allows for two <em>parallel</em> lines, meaning the <code>mpg</code> can be different on average between foreign and domestic cars of the same engine displacement, but the change in average <code>mpg</code> for an increase in displacement is the same for both. We can see this model isn’t doing very well here. The red line fits the red points fairly well, but the black line isn’t doing very well for the black points, it should clearly have a more negative slope. Essentially, we would like a model that allows for two different slopes.</p>
<p>Consider the following model,</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_1 x_2 + \epsilon,
\]</span></p>
<p>where <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, and <span class="math inline">\(Y\)</span> are the same as before, but we have added a new <strong>interaction</strong> term <span class="math inline">\(x_1 x_2\)</span> which multiplies <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>, so we also have an additional <span class="math inline">\(\beta\)</span> parameter <span class="math inline">\(\beta_3\)</span>.</p>
<p>This model essentially creates two slopes and two intercepts, <span class="math inline">\(\beta_2\)</span> being the difference in intercepts and <span class="math inline">\(\beta_3\)</span> being the difference in slopes. To see this, we will break down the model into the two “sub-models” for foreign and domestic cars.</p>
<p>For foreign cars, that is <span class="math inline">\(x_2 = 0\)</span>, we have</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x_1 + \epsilon.
\]</span></p>
<p>For domestic cars, that is <span class="math inline">\(x_2 = 1\)</span>, we have</p>
<p><span class="math display">\[
Y = (\beta_0 + \beta_2) + (\beta_1 + \beta_3) x_1 + \epsilon.
\]</span></p>
<p>These two models have both different slopes and intercepts.</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> is the average <code>mpg</code> for a foreign car with <strong>0</strong> <code>disp</code>.</li>
<li><span class="math inline">\(\beta_1\)</span> is the change in average <code>mpg</code> for an increase of one <code>disp</code>, for <strong>foreign</strong> cars.</li>
<li><span class="math inline">\(\beta_0 + \beta_2\)</span> is the average <code>mpg</code> for a domestic car with <strong>0</strong> <code>disp</code>.</li>
<li><span class="math inline">\(\beta_1 + \beta_3\)</span> is the change in average <code>mpg</code> for an increase of one <code>disp</code>, for <strong>domestic</strong> cars.</li>
</ul>
<p>How do we fit this model in <code>R</code>? There are a number of ways.</p>
<p>One method would be to simply create a new variable, then fit a model like any other.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>autompg<span class="sc">$</span>x3 <span class="ot">=</span> autompg<span class="sc">$</span>disp <span class="sc">*</span> autompg<span class="sc">$</span>domestic <span class="co"># THIS CODE NOT RUN!</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>do_not_do_this <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">+</span> domestic <span class="sc">+</span> x3, <span class="at">data =</span> autompg) <span class="co"># THIS CODE NOT RUN!</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You should only do this as a last resort. We greatly prefer not to have to modify our data simply to fit a model. Instead, we can tell <code>R</code> we would like to use the existing data with an interaction term, which it will create automatically when we use the <code>:</code> operator.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mpg_disp_int <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">+</span> domestic <span class="sc">+</span> disp<span class="sc">:</span>domestic, <span class="at">data =</span> autompg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>An alternative method, which will fit the exact same model as above would be to use the <code>*</code> operator. This method automatically creates the interaction term, as well as any “lower order terms,” which in this case are the first order terms for <code>disp</code> and <code>domestic</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>mpg_disp_int2 <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">*</span> domestic, <span class="at">data =</span> autompg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can quickly verify that these are doing the same thing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mpg_disp_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)          disp      domestic disp:domestic 
   46.0548423    -0.1569239   -12.5754714     0.1025184 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mpg_disp_int2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)          disp      domestic disp:domestic 
   46.0548423    -0.1569239   -12.5754714     0.1025184 </code></pre>
</div>
</div>
<p>We see that both the variables, and their coefficient estimates are indeed the same for both models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mpg_disp_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ disp + domestic + disp:domestic, data = autompg)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.8332  -2.8956  -0.8332   2.2828  18.7749 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    46.05484    1.80582  25.504  &lt; 2e-16 ***
disp           -0.15692    0.01668  -9.407  &lt; 2e-16 ***
domestic      -12.57547    1.95644  -6.428 3.90e-10 ***
disp:domestic   0.10252    0.01692   6.060 3.29e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.308 on 379 degrees of freedom
Multiple R-squared:  0.7011,    Adjusted R-squared:  0.6987 
F-statistic: 296.3 on 3 and 379 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We see that using <code>summary()</code> gives the usual output for a multiple regression model. We pay close attention to the row for <code>disp:domestic</code> which tests,</p>
<p><span class="math display">\[
H_0: \beta_3 = 0.
\]</span></p>
<p>In this case, testing for <span class="math inline">\(\beta_3 = 0\)</span> is testing for two lines with parallel slopes versus two lines with possibly different slopes. The <code>disp:domestic</code> line in the <code>summary()</code> output uses a <span class="math inline">\(t\)</span>-test to perform the test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>int_for <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_int)[<span class="dv">1</span>]</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>int_dom <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_int)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(mpg_disp_int)[<span class="dv">3</span>]</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>slope_for <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_int)[<span class="dv">2</span>]</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>slope_dom <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_int)[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">coef</span>(mpg_disp_int)[<span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here we again calculate the slope and intercepts for the two lines for use in plotting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(autompg, <span class="fu">aes</span>(<span class="at">x =</span> disp, <span class="at">y =</span> mpg, <span class="at">col =</span> <span class="fu">as.factor</span>(domestic))) <span class="sc">+</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> int_dom, </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope =</span> slope_dom, <span class="at">col =</span> <span class="st">'blue'</span>) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> int_for,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope =</span> slope_for, <span class="at">col =</span> <span class="st">'red'</span>) <span class="sc">+</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">'Origin'</span>) <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Foreign'</span>,<span class="st">'Domestic'</span>), <span class="at">values =</span> <span class="fu">c</span>(<span class="st">'red'</span>,<span class="st">'blue'</span>)) <span class="sc">+</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07b_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see that these lines fit the data much better, which matches the result of our tests.</p>
<p>So far we have only seen interaction between a categorical variable (<code>domestic</code>) and a numerical variable (<code>disp</code>). While this is easy to visualize, since it allows for different slopes for two lines, it is not the only type of interaction we can use in a model. We can also consider interactions between two numerical variables.</p>
<p>Consider the model,</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_1 x_2 + \epsilon,
\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(Y\)</span> is <code>mpg</code>, the fuel efficiency in miles per gallon,</li>
<li><span class="math inline">\(x_1\)</span> is <code>disp</code>, the displacement in cubic inches,</li>
<li><span class="math inline">\(x_2\)</span> is <code>hp</code>, the horsepower, in foot-pounds per second.</li>
</ul>
<p>How does <code>mpg</code> change based on <code>disp</code> in this model? We can rearrange some terms to see how.</p>
<p><span class="math display">\[
Y = \beta_0 + (\beta_1 + \beta_3 x_2) x_1 + \beta_2 x_2 + \epsilon
\]</span></p>
<p>So, for a one unit increase in <span class="math inline">\(x_1\)</span> (<code>disp</code>), the mean of <span class="math inline">\(Y\)</span> (<code>mpg</code>) increases <span class="math inline">\(\beta_1 + \beta_3 x_2\)</span>, which is a different value depending on the value of <span class="math inline">\(x_2\)</span> (<code>hp</code>)!</p>
<p>Since we’re now working in three dimensions, this model can’t be easily justified via visualizations like the previous example. Instead, we will have to rely on a test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>mpg_disp_add_hp <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">+</span> hp, <span class="at">data =</span> autompg)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>mpg_disp_int_hp <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">*</span> hp, <span class="at">data =</span> autompg)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mpg_disp_int_hp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ disp * hp, data = autompg)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.7849  -2.3104  -0.5699   2.1453  17.9211 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.241e+01  1.523e+00   34.42   &lt;2e-16 ***
disp        -1.002e-01  6.638e-03  -15.09   &lt;2e-16 ***
hp          -2.198e-01  1.987e-02  -11.06   &lt;2e-16 ***
disp:hp      5.658e-04  5.165e-05   10.96   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.896 on 379 degrees of freedom
Multiple R-squared:  0.7554,    Adjusted R-squared:  0.7535 
F-statistic: 390.2 on 3 and 379 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Using <code>summary()</code> we focus on the row for <code>disp:hp</code> which tests,</p>
<p><span class="math display">\[
H_0: \beta_3 = 0.
\]</span></p>
<p>Again, we see a very low p-value so we reject the null (additive model) in favor of the interaction model. We can take a closer look at the coefficients of our fitted interaction model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mpg_disp_int_hp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)          disp            hp       disp:hp 
52.4081997848 -0.1001737655 -0.2198199720  0.0005658269 </code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(\hat{\beta}_0 = 52.4081998\)</span> is the estimated average <code>mpg</code> for a car with 0 <code>disp</code> and 0 <code>hp</code>.</li>
<li><span class="math inline">\(\hat{\beta}_1 = -0.1001738\)</span> is the estimated change in average <code>mpg</code> for an increase in 1 <code>disp</code>, <strong>for a car with 0 <code>hp</code></strong>.</li>
<li><span class="math inline">\(\hat{\beta}_2 = -0.21982\)</span> is the estimated change in average <code>mpg</code> for an increase in 1 <code>hp</code>, <strong>for a car with 0 <code>disp</code></strong>.</li>
<li><span class="math inline">\(\hat{\beta}_3 = 5.658269\times 10^{-4}\)</span> is an estimate of the modification to the change in average <code>mpg</code> for an increase in <code>disp</code>, for a car of a certain <code>hp</code> (or vice versa).</li>
</ul>
<p>That last coefficient needs further explanation. Recall the rearrangement we made earlier</p>
<p><span class="math display">\[
Y = \beta_0 + (\beta_1 + \beta_3 x_2) x_1 + \beta_2 x_2 + \epsilon.
\]</span></p>
<p>So, our estimate for <span class="math inline">\(\beta_1 + \beta_3 x_2\)</span>, is <span class="math inline">\(\hat{\beta}_1 + \hat{\beta}_3 x_2\)</span>, which in this case is</p>
<p><span class="math display">\[
-0.1001738 + 5.658269\times 10^{-4} x_2.
\]</span></p>
<p>This says that, for an increase of one <code>disp</code> we see an estimated change in average <code>mpg</code> of <span class="math inline">\(-0.1001738 + 5.658269\times 10^{-4} x_2\)</span>. So how <code>disp</code> and <code>mpg</code> are related, depends on the <code>hp</code> of the car.</p>
<p>So for a car with 50 <code>hp</code>, the estimated change in average <code>mpg</code> for an increase of one <code>disp</code> is</p>
<p><span class="math display">\[
-0.1001738 + 5.658269\times 10^{-4} \cdot 50 = -0.0718824
\]</span></p>
<p>And for a car with 350 <code>hp</code>, the estimated change in average <code>mpg</code> for an increase of one <code>disp</code> is</p>
<p><span class="math display">\[
-0.1001738 + 5.658269\times 10^{-4} \cdot 350 = 0.0978657
\]</span></p>
<p>Notice the sign changed!</p>
</section>
<section id="factor-variables" class="level2">
<h2 class="anchored" data-anchor-id="factor-variables">Factor Variables</h2>
<p>So far in this chapter, we have limited our use of categorical variables to binary categorical variables. Specifically, we have limited ourselves to dummy variables which take a value of <code>0</code> or <code>1</code> and represent a categorical variable numerically.</p>
<p>We will now discuss <strong>factor</strong> variables, which is a special way that <code>R</code> deals with categorical variables. With factor variables, a human user can simply think about the categories of a variable, and <code>R</code> will take care of the necessary dummy variables without any 0/1 assignment being done by the user.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(autompg<span class="sc">$</span>domestic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>Earlier when we used the <code>domestic</code> variable, it was <strong>not</strong> a factor variable. It was simply a numerical variable that only took two possible values, <code>1</code> for domestic, and <code>0</code> for foreign. Let’s create a new variable <code>origin</code> that stores the same information, but in a different way. First, we create an empty (all-<code>NA</code>) variable of type <code>character</code>. Then, we update it. Yes, we could also do this with <code>ifelse</code> or <code>case_when</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>autompg<span class="sc">$</span>origin <span class="ot">=</span> <span class="fu">as.character</span>(<span class="cn">NA</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>autompg<span class="sc">$</span>origin[autompg<span class="sc">$</span>domestic <span class="sc">==</span> <span class="dv">1</span>] <span class="ot">=</span> <span class="st">"domestic"</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>autompg<span class="sc">$</span>origin[autompg<span class="sc">$</span>domestic <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">=</span> <span class="st">"foreign"</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(autompg<span class="sc">$</span>origin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "domestic" "domestic" "domestic" "domestic" "domestic" "domestic"</code></pre>
</div>
</div>
<p>Now the <code>origin</code> variable stores <code>"domestic"</code> for domestic cars and <code>"foreign"</code> for foreign cars.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(autompg<span class="sc">$</span>origin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>However, this is simply a vector of character values. A vector of car models is a character variable in <code>R</code>. A vector of Vehicle Identification Numbers (VINs) is a character variable as well. But those don’t represent a short list of levels that might influence a response variable. We will want to <strong>coerce</strong> this origin variable to be something more: a factor variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>autompg<span class="sc">$</span>origin <span class="ot">=</span> <span class="fu">as.factor</span>(autompg<span class="sc">$</span>origin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now when we check the structure of the <code>autompg</code> dataset, we see that <code>origin</code> is a factor variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(autompg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   383 obs. of  10 variables:
 $ mpg     : num  18 15 18 16 17 15 14 14 14 15 ...
 $ cyl     : Factor w/ 3 levels "4","6","8": 3 3 3 3 3 3 3 3 3 3 ...
 $ disp    : num  307 350 318 304 302 429 454 440 455 390 ...
 $ hp      : num  130 165 150 150 140 198 220 215 225 190 ...
 $ wt      : num  3504 3693 3436 3433 3449 ...
 $ acc     : num  12 11.5 11 12 10.5 10 9 8.5 10 8.5 ...
 $ year    : int  70 70 70 70 70 70 70 70 70 70 ...
 $ origin  : Factor w/ 2 levels "domestic","foreign": 1 1 1 1 1 1 1 1 1 1 ...
 $ name    : chr  "chevrolet chevelle malibu" "buick skylark 320" "plymouth satellite" "amc rebel sst" ...
 $ domestic: num  1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>Factor variables have <strong>levels</strong> which are the possible values (categories) that the variable may take, in this case foreign or domestic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(autompg<span class="sc">$</span>origin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "domestic" "foreign" </code></pre>
</div>
</div>
<p>Recall that previously we have fit the model</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_1 x_2 + \epsilon,
\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(Y\)</span> is <code>mpg</code>, the fuel efficiency in miles per gallon,</li>
<li><span class="math inline">\(x_1\)</span> is <code>disp</code>, the displacement in cubic inches,</li>
<li><span class="math inline">\(x_2\)</span> is <code>domestic</code> a dummy variable where <code>1</code> indicates a domestic car.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">mod_dummy =</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">*</span> domestic, <span class="at">data =</span> autompg))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ disp * domestic, data = autompg)

Coefficients:
  (Intercept)           disp       domestic  disp:domestic  
      46.0548        -0.1569       -12.5755         0.1025  </code></pre>
</div>
</div>
<p>So here we see that</p>
<p><span class="math display">\[
\hat{\beta}_0 + \hat{\beta}_2 = 46.0548423 + -12.5754714 = 33.4793709
\]</span></p>
<p>is the estimated average <code>mpg</code> for a <strong>domestic</strong> car with 0 <code>disp</code>.</p>
<p>Now let’s try to do the same, but using our new factor variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">mod_factor =</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">*</span> origin, <span class="at">data =</span> autompg))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ disp * origin, data = autompg)

Coefficients:
       (Intercept)                disp       originforeign  disp:originforeign  
          33.47937            -0.05441            12.57547            -0.10252  </code></pre>
</div>
</div>
<p>It seems that it doesn’t produce the same results. Right away we notice that the intercept is different, as is the the coefficient in front of <code>disp</code>. We also notice that the remaining two coefficients are of the same magnitude as their respective counterparts using the domestic variable, but with a different sign. Why is this happening?</p>
<p>It turns out, that by using a factor variable, <code>R</code> is automatically creating a dummy variable for us. However, it is not the dummy variable that we had originally used ourselves.</p>
<p><code>R</code> is fitting the model</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_1 x_2 + \epsilon,
\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(Y\)</span> is <code>mpg</code>, the fuel efficiency in miles per gallon,</li>
<li><span class="math inline">\(x_1\)</span> is <code>disp</code>, the displacement in cubic inches,</li>
<li><span class="math inline">\(x_2\)</span> <strong>is a dummy variable created by <code>R</code>.</strong> It uses <code>1</code> to represent a <strong>foreign car</strong>.</li>
</ul>
<p>You may recall that we saw this in action in Assignment 05 when we used <code>model.matrix</code> on <code>GarageType</code>.</p>
<p>So now,</p>
<p><span class="math display">\[
\hat{\beta}_0 = 33.4793709
\]</span></p>
<p>is the estimated average <code>mpg</code> for a <strong>domestic</strong> car with 0 <code>disp</code>, which is indeed the same as before.</p>
<p>When <code>R</code> created <span class="math inline">\(x_2\)</span>, the dummy variable, it used domestic cars as the <strong>reference</strong> level, that is the default value of the factor variable. So when the dummy variable is <code>0</code>, the model represents this reference level, which is domestic. (<code>R</code> makes this choice because domestic comes before foreign alphabetically.)</p>
<p>So the two models have different estimated coefficients, but due to the different model representations, they are actually the same model.</p>
<section id="factors-with-more-than-two-levels" class="level3">
<h3 class="anchored" data-anchor-id="factors-with-more-than-two-levels">Factors with More Than Two Levels</h3>
<p>Let’s now consider a factor variable with more than two levels. In this dataset, <code>cyl</code> is an example.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(autompg<span class="sc">$</span>cyl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(autompg<span class="sc">$</span>cyl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "4" "6" "8"</code></pre>
</div>
</div>
<p>Here the <code>cyl</code> variable has three possible levels: <code>4</code>, <code>6</code>, and <code>8</code>. You may wonder, why not simply use <code>cyl</code> as a numerical variable? You certainly could.</p>
<p>However, that would force the difference in average <code>mpg</code> between <code>4</code> and <code>6</code> cylinders to be the same as the difference in average mpg between <code>6</code> and <code>8</code> cylinders. That usually make senses for a continuous variable, but not for a discrete variable with so few possible values. In the case of this variable, there is no such thing as a 7-cylinder engine or a 6.23-cylinder engine in personal vehicles. For these reasons, we will simply consider <code>cyl</code> to be categorical. This is a decision that will commonly need to be made with ordinal variables. Often, with a large number of categories, the decision to treat them as numerical variables is appropriate because, otherwise, a large number of dummy variables are then needed to represent these variables.</p>
<p>Let’s define three dummy variables related to the <code>cyl</code> factor variable.</p>
<p><span class="math display">\[
v_1 =
  \begin{cases}
   1 &amp; \text{4 cylinder} \\
   0       &amp; \text{not 4 cylinder}
  \end{cases}
\]</span></p>
<p><span class="math display">\[
v_2 =
  \begin{cases}
   1 &amp; \text{6 cylinder} \\
   0       &amp; \text{not 6 cylinder}
  \end{cases}
\]</span></p>
<p><span class="math display">\[
v_3 =
  \begin{cases}
   1 &amp; \text{8 cylinder} \\
   0       &amp; \text{not 8 cylinder}
  \end{cases}
\]</span></p>
<p>Now, let’s fit an additive model in <code>R</code>, using <code>mpg</code> as the response, and <code>disp</code> and <code>cyl</code> as predictors. This should be a model that uses “three regression lines” to model <code>mpg</code>, one for each of the possible <code>cyl</code> levels. They will all have the same slope (since it is an additive model), but each will have its own intercept.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">mpg_disp_add_cyl =</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">+</span> cyl, <span class="at">data =</span> autompg))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ disp + cyl, data = autompg)

Coefficients:
(Intercept)         disp         cyl6         cyl8  
   34.99929     -0.05217     -3.63325     -2.03603  </code></pre>
</div>
</div>
<p>The question is, what is the model that <code>R</code> has fit here? It has chosen to use the model</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x + \beta_2 v_2 + \beta_3 v_3 + \epsilon,
\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(Y\)</span> is <code>mpg</code>, the fuel efficiency in miles per gallon,</li>
<li><span class="math inline">\(x\)</span> is <code>disp</code>, the displacement in cubic inches,</li>
<li><span class="math inline">\(v_2\)</span> and <span class="math inline">\(v_3\)</span> are the dummy variables define above.</li>
</ul>
<p>Why doesn’t <code>R</code> use <span class="math inline">\(v_1\)</span>? Essentially because it doesn’t need to. To create three lines, it only needs two dummy variables since it is using a reference level, which in this case is a 4 cylinder car. The three “sub models” are then:</p>
<ul>
<li>4 Cylinder: <span class="math inline">\(Y = \beta_0 + \beta_1 x + \epsilon\)</span></li>
<li>6 Cylinder: <span class="math inline">\(Y = (\beta_0 + \beta_2) + \beta_1 x + \epsilon\)</span></li>
<li>8 Cylinder: <span class="math inline">\(Y = (\beta_0 + \beta_3) + \beta_1 x + \epsilon\)</span></li>
</ul>
<p>Notice that they all have the same slope. However, using the two dummy variables, we achieve the three intercepts.</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> is the average <code>mpg</code> for a 4 cylinder car with 0 <code>disp</code>.</li>
<li><span class="math inline">\(\beta_0 + \beta_2\)</span> is the average <code>mpg</code> for a 6 cylinder car with 0 <code>disp</code>.</li>
<li><span class="math inline">\(\beta_0 + \beta_3\)</span> is the average <code>mpg</code> for a 8 cylinder car with 0 <code>disp</code>.</li>
</ul>
<p>So because 4 cylinder is the reference level, <span class="math inline">\(\beta_0\)</span> is specific to 4 cylinders, but <span class="math inline">\(\beta_2\)</span> and <span class="math inline">\(\beta_3\)</span> are used to represent quantities relative to 4 cylinders.</p>
<p>As we have done before, we can extract these intercepts and slopes for the three lines, and plot them accordingly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>int_4cyl <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_add_cyl)[<span class="dv">1</span>]</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>int_6cyl <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_add_cyl)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(mpg_disp_add_cyl)[<span class="dv">3</span>]</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>int_8cyl <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_add_cyl)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(mpg_disp_add_cyl)[<span class="dv">4</span>]</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>slope_all_cyl <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_add_cyl)[<span class="dv">2</span>]</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>plot_colors <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Darkorange"</span>, <span class="st">"Darkgrey"</span>, <span class="st">"Dodgerblue"</span>)</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpg <span class="sc">~</span> disp, <span class="at">data =</span> autompg, <span class="at">col =</span> plot_colors[cyl], <span class="at">pch =</span> <span class="fu">as.numeric</span>(cyl))</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(int_4cyl, slope_all_cyl, <span class="at">col =</span> plot_colors[<span class="dv">1</span>], <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(int_6cyl, slope_all_cyl, <span class="at">col =</span> plot_colors[<span class="dv">2</span>], <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(int_8cyl, slope_all_cyl, <span class="at">col =</span> plot_colors[<span class="dv">3</span>], <span class="at">lty =</span> <span class="dv">3</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="fu">c</span>(<span class="st">"4 Cylinder"</span>, <span class="st">"6 Cylinder"</span>, <span class="st">"8 Cylinder"</span>),</span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> plot_colors, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07b_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>On this plot, we have</p>
<ul>
<li>4 Cylinder: orange dots, solid orange line.</li>
<li>6 Cylinder: grey dots, dashed grey line.</li>
<li>8 Cylinder: blue dots, dotted blue line.</li>
</ul>
<p>The odd result here is that we’re estimating that 8 cylinder cars have better fuel efficiency than 6 cylinder cars at <strong>any</strong> displacement! The dotted blue line is always above the dashed grey line. That doesn’t seem right. Maybe for very large displacement engines that could be true, but that seems wrong for medium to low displacement.</p>
<p>To attempt to fix this, we will try using an interaction model, that is, instead of simply three intercepts and one slope, we will allow for three slopes. Again, we’ll let <code>R</code> take the wheel, (no pun intended) then figure out what model it has applied.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">mpg_disp_int_cyl =</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">*</span> cyl, <span class="at">data =</span> autompg))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ disp * cyl, data = autompg)

Coefficients:
(Intercept)         disp         cyl6         cyl8    disp:cyl6    disp:cyl8  
   43.59052     -0.13069    -13.20026    -20.85706      0.08299      0.10817  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># could also use mpg ~ disp + cyl + disp:cyl</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>R</code> has again chosen to use 4 cylinder cars as the reference level, but this also now has an effect on the interaction terms. <code>R</code> has fit the model.</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x + \beta_2 v_2 + \beta_3 v_3 + \gamma_2 x v_2 + \gamma_3 x v_3 + \epsilon
\]</span></p>
<p>We’re using <span class="math inline">\(\gamma\)</span> like a <span class="math inline">\(\beta\)</span> parameter for simplicity, so that, for example <span class="math inline">\(\beta_2\)</span> and <span class="math inline">\(\gamma_2\)</span> are both associated with <span class="math inline">\(v_2\)</span>.</p>
<p>Now, the three “sub models” are:</p>
<ul>
<li>4 Cylinder: <span class="math inline">\(Y = \beta_0 + \beta_1 x + \epsilon\)</span>.</li>
<li>6 Cylinder: <span class="math inline">\(Y = (\beta_0 + \beta_2) + (\beta_1 + \gamma_2) x + \epsilon\)</span>.</li>
<li>8 Cylinder: <span class="math inline">\(Y = (\beta_0 + \beta_3) + (\beta_1 + \gamma_3) x + \epsilon\)</span>.</li>
</ul>
<p>Interpreting some parameters and coefficients then:</p>
<ul>
<li><span class="math inline">\((\beta_0 + \beta_2)\)</span> is the average <code>mpg</code> of a 6 cylinder car with 0 <code>disp</code></li>
<li><span class="math inline">\((\hat{\beta}_1 + \hat{\gamma}_3) = -0.1306935 + 0.1081714 = -0.0225221\)</span> is the estimated change in average <code>mpg</code> for an increase of one <code>disp</code>, for an 8 cylinder car.</li>
</ul>
<p>So, as we have seen before <span class="math inline">\(\beta_2\)</span> and <span class="math inline">\(\beta_3\)</span> change the intercepts for 6 and 8 cylinder cars relative to the reference level of <span class="math inline">\(\beta_0\)</span> for 4 cylinder cars.</p>
<p>Now, similarly <span class="math inline">\(\gamma_2\)</span> and <span class="math inline">\(\gamma_3\)</span> change the slopes for 6 and 8 cylinder cars relative to the reference level of <span class="math inline">\(\beta_1\)</span> for 4 cylinder cars.</p>
<p>Once again, we extract the coefficients and plot the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>int_4cyl <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_int_cyl)[<span class="dv">1</span>]</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>int_6cyl <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_int_cyl)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(mpg_disp_int_cyl)[<span class="dv">3</span>]</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>int_8cyl <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_int_cyl)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(mpg_disp_int_cyl)[<span class="dv">4</span>]</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>slope_4cyl <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_int_cyl)[<span class="dv">2</span>]</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>slope_6cyl <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_int_cyl)[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">coef</span>(mpg_disp_int_cyl)[<span class="dv">5</span>]</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>slope_8cyl <span class="ot">=</span> <span class="fu">coef</span>(mpg_disp_int_cyl)[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">coef</span>(mpg_disp_int_cyl)[<span class="dv">6</span>]</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>plot_colors <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Darkorange"</span>, <span class="st">"Darkgrey"</span>, <span class="st">"Dodgerblue"</span>)</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpg <span class="sc">~</span> disp, <span class="at">data =</span> autompg, <span class="at">col =</span> plot_colors[cyl], <span class="at">pch =</span> <span class="fu">as.numeric</span>(cyl))</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(int_4cyl, slope_4cyl, <span class="at">col =</span> plot_colors[<span class="dv">1</span>], <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(int_6cyl, slope_6cyl, <span class="at">col =</span> plot_colors[<span class="dv">2</span>], <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(int_8cyl, slope_8cyl, <span class="at">col =</span> plot_colors[<span class="dv">3</span>], <span class="at">lty =</span> <span class="dv">3</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="fu">c</span>(<span class="st">"4 Cylinder"</span>, <span class="st">"6 Cylinder"</span>, <span class="st">"8 Cylinder"</span>),</span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> plot_colors, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07b_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This looks much better! We can see that for medium displacement cars, 6 cylinder cars now perform better than 8 cylinder cars, which seems much more reasonable than before.</p>
<p>To completely justify the interaction model (i.e., a unique slope for each <code>cyl</code> level) compared to the additive model (single slope), we can perform an <span class="math inline">\(F\)</span>-test. Notice first, that there is no <span class="math inline">\(t\)</span>-test that will be able to do this since the difference between the two models is not a single parameter.</p>
<p>We will test,</p>
<p><span class="math display">\[
H_0: \gamma_2 = \gamma_3 = 0
\]</span></p>
<p>which represents the parallel regression lines we saw before,</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x + \beta_2 v_2 + \beta_3 v_3 + \epsilon.
\]</span></p>
<p>Again, this is a difference of two parameters, thus no <span class="math inline">\(t\)</span>-test will be useful.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mpg_disp_add_cyl, mpg_disp_int_cyl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: mpg ~ disp + cyl
Model 2: mpg ~ disp * cyl
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1    379 7299.5                                  
2    377 6551.7  2    747.79 21.515 1.419e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>As expected, we see a very low p-value, and thus reject the null. We prefer the interaction model over the additive model.</p>
<p>Recapping a bit:</p>
<ul>
<li>Null Model: <span class="math inline">\(Y = \beta_0 + \beta_1 x + \beta_2 v_2 + \beta_3 v_3 + \epsilon\)</span>
<ul>
<li>Number of parameters: <span class="math inline">\(q = 4\)</span></li>
</ul></li>
<li>Full Model: <span class="math inline">\(Y = \beta_0 + \beta_1 x + \beta_2 v_2 + \beta_3 v_3 + \gamma_2 x v_2 + \gamma_3 x v_3 + \epsilon\)</span>
<ul>
<li>Number of parameters: <span class="math inline">\(p = 6\)</span></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">coef</span>(mpg_disp_int_cyl)) <span class="sc">-</span> <span class="fu">length</span>(<span class="fu">coef</span>(mpg_disp_add_cyl))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>We see there is a difference of two parameters, which is also displayed in the resulting ANOVA table from <code>R</code>. Notice that the following two values also appear on the ANOVA table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(autompg) <span class="sc">-</span> <span class="fu">length</span>(<span class="fu">coef</span>(mpg_disp_int_cyl))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 377</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(autompg) <span class="sc">-</span> <span class="fu">length</span>(<span class="fu">coef</span>(mpg_disp_add_cyl))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 379</code></pre>
</div>
</div>
</section>
</section>
<section id="parameterization" class="level2">
<h2 class="anchored" data-anchor-id="parameterization">Parameterization</h2>
<p>So far we have been simply letting <code>R</code> decide how to create the dummy variables, and thus <code>R</code> has been deciding the parameterization of the models. To illustrate the ability to use alternative parameterizations, we will recreate the data, but directly creating the dummy variables ourselves.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>new_param_data <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> autompg<span class="sc">$</span>mpg,</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> autompg<span class="sc">$</span>disp,</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">v1 =</span> <span class="dv">1</span> <span class="sc">*</span> <span class="fu">as.numeric</span>(autompg<span class="sc">$</span>cyl <span class="sc">==</span> <span class="dv">4</span>),</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">v2 =</span> <span class="dv">1</span> <span class="sc">*</span> <span class="fu">as.numeric</span>(autompg<span class="sc">$</span>cyl <span class="sc">==</span> <span class="dv">6</span>),</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">v3 =</span> <span class="dv">1</span> <span class="sc">*</span> <span class="fu">as.numeric</span>(autompg<span class="sc">$</span>cyl <span class="sc">==</span> <span class="dv">8</span>))</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(new_param_data, <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    y   x v1 v2 v3
1  18 307  0  0  1
2  15 350  0  0  1
3  18 318  0  0  1
4  16 304  0  0  1
5  17 302  0  0  1
6  15 429  0  0  1
7  14 454  0  0  1
8  14 440  0  0  1
9  14 455  0  0  1
10 15 390  0  0  1
11 15 383  0  0  1
12 14 340  0  0  1
13 15 400  0  0  1
14 14 455  0  0  1
15 24 113  1  0  0
16 22 198  0  1  0
17 18 199  0  1  0
18 21 200  0  1  0
19 27  97  1  0  0
20 26  97  1  0  0</code></pre>
</div>
</div>
<p>Now,</p>
<ul>
<li><code>y</code> is <code>mpg</code></li>
<li><code>x</code> is <code>disp</code>, the displacement in cubic inches,</li>
<li><code>v1</code>, <code>v2</code>, and <code>v3</code> are dummy variables as defined above.</li>
</ul>
<p>First let’s try to fit an additive model using <code>x</code> as well as the three dummy variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> v1 <span class="sc">+</span> v2 <span class="sc">+</span> v3, <span class="at">data =</span> new_param_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x + v1 + v2 + v3, data = new_param_data)

Coefficients:
(Intercept)            x           v1           v2           v3  
   32.96326     -0.05217      2.03603     -1.59722           NA  </code></pre>
</div>
</div>
<p>What is happening here? Notice that <code>R</code> is essentially ignoring <code>v3</code>, but why? Well, because <code>R</code> uses an intercept, it cannot also use <code>v3</code>. This is because</p>
<p><span class="math display">\[
\boldsymbol{1} = v_1 + v_2 + v_3
\]</span></p>
<p>which means that <span class="math inline">\(\boldsymbol{1}\)</span>, <span class="math inline">\(v_1\)</span>, <span class="math inline">\(v_2\)</span>, and <span class="math inline">\(v_3\)</span> are linearly dependent. This would make the <span class="math inline">\(X^\top X\)</span> matrix singular, but we need to be able to invert it to solve the normal equations and obtain <span class="math inline">\(\hat{\beta}.\)</span> With the intercept, <code>v1</code>, and <code>v2</code>, <code>R</code> can make the necessary “three intercepts”. So, in this case <code>v3</code> is the reference level.</p>
<p>If we remove the intercept, then we can directly obtain all “three intercepts” without a reference level.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> x <span class="sc">+</span> v1 <span class="sc">+</span> v2 <span class="sc">+</span> v3, <span class="at">data =</span> new_param_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ 0 + x + v1 + v2 + v3, data = new_param_data)

Coefficients:
       x        v1        v2        v3  
-0.05217  34.99929  31.36604  32.96326  </code></pre>
</div>
</div>
<p>Here, we are fitting the model</p>
<p><span class="math display">\[
Y = \mu_1 v_1 + \mu_2 v_2 + \mu_3 v_3 + \beta x +\epsilon.
\]</span></p>
<p>Thus we have:</p>
<ul>
<li>4 Cylinder: <span class="math inline">\(Y = \mu_1 + \beta x + \epsilon\)</span></li>
<li>6 Cylinder: <span class="math inline">\(Y = \mu_2 + \beta x + \epsilon\)</span></li>
<li>8 Cylinder: <span class="math inline">\(Y = \mu_3 + \beta x + \epsilon\)</span></li>
</ul>
<p>We could also do something similar with the interaction model, and give each line an intercept and slope, without the need for a reference level.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> v1 <span class="sc">+</span> v2 <span class="sc">+</span> v3 <span class="sc">+</span> x<span class="sc">:</span>v1 <span class="sc">+</span> x<span class="sc">:</span>v2 <span class="sc">+</span> x<span class="sc">:</span>v3, <span class="at">data =</span> new_param_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ 0 + v1 + v2 + v3 + x:v1 + x:v2 + x:v3, data = new_param_data)

Coefficients:
      v1        v2        v3      v1:x      v2:x      v3:x  
43.59052  30.39026  22.73346  -0.13069  -0.04770  -0.02252  </code></pre>
</div>
</div>
<p><span class="math display">\[
Y = \mu_1 v_1 + \mu_2 v_2 + \mu_3 v_3 + \beta_1 x v_1 + \beta_2 x v_2 + \beta_3 x v_3 +\epsilon
\]</span></p>
<ul>
<li>4 Cylinder: <span class="math inline">\(Y = \mu_1 + \beta_1 x + \epsilon\)</span></li>
<li>6 Cylinder: <span class="math inline">\(Y = \mu_2 + \beta_2 x + \epsilon\)</span></li>
<li>8 Cylinder: <span class="math inline">\(Y = \mu_3 + \beta_3 x + \epsilon\)</span></li>
</ul>
<p>Using the original data, we have (at least) three equivalent ways to specify the interaction model with <code>R</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">*</span> cyl, <span class="at">data =</span> autompg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ disp * cyl, data = autompg)

Coefficients:
(Intercept)         disp         cyl6         cyl8    disp:cyl6    disp:cyl8  
   43.59052     -0.13069    -13.20026    -20.85706      0.08299      0.10817  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(mpg <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> cyl <span class="sc">+</span> disp <span class="sc">:</span> cyl, <span class="at">data =</span> autompg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ 0 + cyl + disp:cyl, data = autompg)

Coefficients:
     cyl4       cyl6       cyl8  cyl4:disp  cyl6:disp  cyl8:disp  
 43.59052   30.39026   22.73346   -0.13069   -0.04770   -0.02252  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(mpg <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> disp <span class="sc">+</span> cyl <span class="sc">+</span> disp <span class="sc">:</span> cyl, <span class="at">data =</span> autompg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ 0 + disp + cyl + disp:cyl, data = autompg)

Coefficients:
     disp       cyl4       cyl6       cyl8  disp:cyl6  disp:cyl8  
 -0.13069   43.59052   30.39026   22.73346    0.08299    0.10817  </code></pre>
</div>
</div>
<p>They all fit the same model, importantly each using six parameters, but the coefficients mean slightly different things in each. However, once they are interpreted as slopes and intercepts for the “three lines” they will have the same result.</p>
<p>Use <code>?all.equal</code> to learn about the <code>all.equal()</code> function, and think about how the following code verifies that the residuals of the two models are the same.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(<span class="fu">fitted</span>(<span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">*</span> cyl, <span class="at">data =</span> autompg)),</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">fitted</span>(<span class="fu">lm</span>(mpg <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> cyl <span class="sc">+</span> disp <span class="sc">:</span> cyl, <span class="at">data =</span> autompg)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<div class="fyi">
<p><strong>TRY IT</strong></p>
<p>Let’s try some interaction terms using our <code>Ames</code> data from before (linked at the top of this page). For now, we’ll stick to interacting square footage (<code>GrLivArea</code>) with dummy or factor variables. As usual, we’re trying to predict <code>SalePrice</code>.</p>
<p>What factor variables should we use? Here are some options:</p>
<ol type="1">
<li><code>CentralAir</code> (binary, but stored as “Y”/“N”)</li>
<li><code>Neighborhood</code> (25 different neighborhoods, stored as <code>chr</code>)</li>
<li><code>YearBuilt</code> (not a factor, but <code>case_when</code> can be used to make a few bins based on year)</li>
<li><code>OverallCond</code> (subjective 1-9 scale, but stored as an integer – use <code>as.factor</code>!)</li>
<li><code>???</code> Anything else interesting you see?</li>
</ol>
<p>I’d like you to choose one of the above and run two models: one with <code>GrLivArea</code> and your chosen factor variable, and one with <code>GrLivArea</code>, your chosen factor variable, <em>and the interaction of the two</em>. Once you have run these:</p>
<ol type="1">
<li>Be prepared to interpret the coefficients on the “baseline” coefficient on <code>GrLivArea</code>, as well as one of the coefficients on the interaction.</li>
<li>Test the two models using <code>anova(mod1, mod2)</code> and tell us if your more flexible model is statistically better than the less flexible model.</li>
</ol>
</div>
</section>
<section id="building-larger-models" class="level2">
<h2 class="anchored" data-anchor-id="building-larger-models">Building Larger Models</h2>
<p>Now that we have seen how to incorporate categorical predictors as well as interaction terms, we can start to build much larger, much more flexible models which can potentially fit data better.</p>
<p>Let’s define a “big” model,</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3 + \beta_4 x_1 x_2 + \beta_5 x_1 x_3 + \beta_6 x_2 x_3 + \beta_7 x_1 x_2 x_3 + \epsilon.
\]</span></p>
<p>Here,</p>
<ul>
<li><span class="math inline">\(Y\)</span> is <code>mpg</code>.</li>
<li><span class="math inline">\(x_1\)</span> is <code>disp</code>.</li>
<li><span class="math inline">\(x_2\)</span> is <code>hp</code>.</li>
<li><span class="math inline">\(x_3\)</span> is <code>domestic</code>, which is a dummy variable we defined, where <code>1</code> is a domestic vehicle.</li>
</ul>
<p>First thing to note here, we have included a new term <span class="math inline">\(x_1 x_2 x_3\)</span> which is a three-way interaction. Interaction terms can be larger and larger, up to the number of predictors in the model.</p>
<p>Since we are using the three-way interaction term, we also use all possible two-way interactions, as well as each of the first order (<strong>main effect</strong>) terms. This is the concept of a <strong>hierarchy</strong>. Any time a “higher-order” term is in a model, the related “lower-order” terms should also be included. Mathematically their inclusion or exclusion is sometimes irrelevant, but from an interpretation standpoint, it is best to follow the hierarchy rules.</p>
<p>Let’s do some rearrangement to obtain a “coefficient” in front of <span class="math inline">\(x_1\)</span>.</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_2 x_2 + \beta_3 x_3 + \beta_6 x_2 x_3 + (\beta_1 + \beta_4 x_2 + \beta_5 x_3 + \beta_7 x_2 x_3)x_1 + \epsilon.
\]</span></p>
<p>Specifically, the “coefficient” in front of <span class="math inline">\(x_1\)</span> is</p>
<p><span class="math display">\[
(\beta_1 + \beta_4 x_2 + \beta_5 x_3 + \beta_7 x_2 x_3).
\]</span></p>
<p>Let’s discuss this “coefficient” to help us understand the idea of the <em>flexibility</em> of a model. Recall that,</p>
<ul>
<li><span class="math inline">\(\beta_1\)</span> is the coefficient for a first order term,</li>
<li><span class="math inline">\(\beta_4\)</span> and <span class="math inline">\(\beta_5\)</span> are coefficients for two-way interactions,</li>
<li><span class="math inline">\(\beta_7\)</span> is the coefficient for the three-way interaction.</li>
</ul>
<p>If the two and three way interactions were not in the model, the whole “coefficient” would simply be</p>
<p><span class="math display">\[
\beta_1.
\]</span></p>
<p>Thus, no matter the values of <span class="math inline">\(x_2\)</span> and <span class="math inline">\(x_3\)</span>, <span class="math inline">\(\beta_1\)</span> would determine the relationship between <span class="math inline">\(x_1\)</span> (<code>disp</code>) and <span class="math inline">\(Y\)</span> (<code>mpg</code>).</p>
<p>With the addition of the two-way interactions, now the “coefficient” would be</p>
<p><span class="math display">\[
(\beta_1 + \beta_4 x_2 + \beta_5 x_3).
\]</span></p>
<p>Now, changing <span class="math inline">\(x_1\)</span> (<code>disp</code>) has a different effect on <span class="math inline">\(Y\)</span> (<code>mpg</code>), depending on the values of <span class="math inline">\(x_2\)</span> and <span class="math inline">\(x_3\)</span>.</p>
<p>Lastly, adding the three-way interaction gives the whole “coefficient”</p>
<p><span class="math display">\[
(\beta_1 + \beta_4 x_2 + \beta_5 x_3 + \beta_7 x_2 x_3)
\]</span></p>
<p>which is even more flexible. Now changing <span class="math inline">\(x_1\)</span> (<code>disp</code>) has a different effect on <span class="math inline">\(Y\)</span> (<code>mpg</code>), depending on the values of <span class="math inline">\(x_2\)</span> and <span class="math inline">\(x_3\)</span>, but in a more flexible way which we can see with some more rearrangement. Now the “coefficient” in front of <span class="math inline">\(x_3\)</span> in this “coefficient” is dependent on <span class="math inline">\(x_2\)</span>.</p>
<p><span class="math display">\[
(\beta_1 + \beta_4 x_2 + (\beta_5 + \beta_7 x_2) x_3)
\]</span></p>
<p>It is so flexible, it is becoming hard to interpret!</p>
<p>Let’s fit this three-way interaction model in <code>R</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>big_model <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">*</span> hp <span class="sc">*</span> domestic, <span class="at">data =</span> autompg)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(big_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ disp * hp * domestic, data = autompg)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.9410  -2.2147  -0.4008   1.9430  18.4094 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       6.065e+01  6.600e+00   9.189  &lt; 2e-16 ***
disp             -1.416e-01  6.344e-02  -2.232   0.0262 *  
hp               -3.545e-01  8.123e-02  -4.364 1.65e-05 ***
domestic         -1.257e+01  7.064e+00  -1.780   0.0759 .  
disp:hp           1.369e-03  6.727e-04   2.035   0.0426 *  
disp:domestic     4.933e-02  6.400e-02   0.771   0.4414    
hp:domestic       1.852e-01  8.709e-02   2.126   0.0342 *  
disp:hp:domestic -9.163e-04  6.768e-04  -1.354   0.1766    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.88 on 375 degrees of freedom
Multiple R-squared:   0.76, Adjusted R-squared:  0.7556 
F-statistic: 169.7 on 7 and 375 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Do we actually need this large of a model? Let’s first test for the necessity of the three-way interaction term. That is,</p>
<p><span class="math display">\[
H_0: \beta_7 = 0.
\]</span></p>
<p>So,</p>
<ul>
<li>Full Model: <span class="math inline">\(Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3 + \beta_4 x_1 x_2 + \beta_5 x_1 x_3 + \beta_6 x_2 x_3 + \beta_7 x_1 x_2 x_3 + \epsilon\)</span></li>
<li>Null Model: <span class="math inline">\(Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3 + \beta_4 x_1 x_2 + \beta_5 x_1 x_3 + \beta_6 x_2 x_3 + \epsilon\)</span></li>
</ul>
<p>We fit the null model in <code>R</code> as <code>two_way_int_mod</code>. Again, we check to see if the big model is any more explanatory:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>two_way_int_mod <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">*</span> hp <span class="sc">+</span> disp <span class="sc">*</span> domestic <span class="sc">+</span> hp <span class="sc">*</span> domestic, <span class="at">data =</span> autompg)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="co">#two_way_int_mod = lm(mpg ~ (disp + hp + domestic) ^ 2, data = autompg)</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(two_way_int_mod, big_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: mpg ~ disp * hp + disp * domestic + hp * domestic
Model 2: mpg ~ disp * hp * domestic
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1    376 5673.2                           
2    375 5645.6  1    27.599 1.8332 0.1766</code></pre>
</div>
</div>
<p>We see the p-value is somewhat large, so we would fail to reject. We prefer the smaller, less flexible, null model, without the three-way interaction.</p>
<p>A quick note here: the full model does still “fit better.” Notice that it has a smaller RMSE than the null model, which means the full model makes smaller (squared) errors on average.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">resid</span>(big_model) <span class="sc">^</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.74053</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">resid</span>(two_way_int_mod) <span class="sc">^</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.81259</code></pre>
</div>
</div>
<p>However, it is not much smaller. We could even say that, the difference is insignificant. This is an idea we will return to later in greater detail.</p>
<p>Now that we have chosen the model without the three-way interaction, can we go further? Do we need the two-way interactions? Let’s test</p>
<p><span class="math display">\[
H_0: \beta_4 = \beta_5 = \beta_6 = 0.
\]</span></p>
<p>Remember we already chose <span class="math inline">\(\beta_7 = 0\)</span>, so,</p>
<ul>
<li>Full Model: <span class="math inline">\(Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3 + \beta_4 x_1 x_2 + \beta_5 x_1 x_3 + \beta_6 x_2 x_3 + \epsilon\)</span></li>
<li>Null Model: <span class="math inline">\(Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3 + \epsilon\)</span></li>
</ul>
<p>We fit the null model in <code>R</code> as <code>additive_mod</code>, then use <code>anova()</code> to perform an <span class="math inline">\(F\)</span>-test as usual.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>additive_mod <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> disp <span class="sc">+</span> hp <span class="sc">+</span> domestic, <span class="at">data =</span> autompg)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(additive_mod, two_way_int_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: mpg ~ disp + hp + domestic
Model 2: mpg ~ disp * hp + disp * domestic + hp * domestic
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1    379 7369.7                                  
2    376 5673.2  3    1696.5 37.478 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Here the p-value is small, so we reject the null, and we prefer the full (alternative) model. Of the models we have considered, our final preference is for</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3 + \beta_4 x_1 x_2 + \beta_5 x_1 x_3 + \beta_6 x_2 x_3 + \epsilon.
\]</span></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>